package ru.astrosmap.app.ui.tarot

import ru.astrosmap.app.ui.AstroLabels

/**
 * Колода Райдера—Уэйта, 78 карт. Только прямое положение — одна трактовка на карту.
 *
 * id совпадает с именем файла в assets/tarot/<id>.webp. Тексты авторские, двуязычные:
 * meaning — суть аркана (с оттенком роста/тени), advice — как применить в течение дня.
 * name/meaning/advice выбираются по языку приложения (AstroLabels.isRu()).
 */
data class TarotCard(
    val id: String,
    val nameRu: String,
    val nameEn: String,
    val meaningRu: String,
    val meaningEn: String,
    val adviceRu: String,
    val adviceEn: String,
) {
    val name: String get() = if (AstroLabels.isRu()) nameRu else nameEn
    val meaning: String get() = if (AstroLabels.isRu()) meaningRu else meaningEn
    val advice: String get() = if (AstroLabels.isRu()) adviceRu else adviceEn
}

object TarotDeck {

    val cards: List<TarotCard> = listOf(
        // --- Старшие арканы ---
        TarotCard("major_00_fool", "Шут", "The Fool",
            "Начало пути, чистый лист и вера в жизнь: готовность шагнуть в новое без груза прошлого. Тень — беспечность и прыжок вслепую.",
            "A fresh start, a clean slate and trust in life: readiness to step into the new without the weight of the past. The shadow is recklessness and leaping blind.",
            "Позвольте себе искренний шаг в неизвестность — маленький, но настоящий. Сегодня уместны лёгкость и любопытство, но смотрите, куда ступаете.",
            "Allow yourself an honest step into the unknown — small but real. Lightness and curiosity fit today, just watch where you land."),
        TarotCard("major_01_magician", "Маг", "The Magician",
            "Воля, мастерство и умение соединять замысел с действием. У вас есть все инструменты, чтобы начать; тень — манипуляция и распыление сил.",
            "Will, skill and the power to turn intention into action. You already hold every tool you need; the shadow is manipulation and scattered focus.",
            "Сформулируйте одно ясное намерение и сделайте по нему конкретный шаг — ресурсы уже в руках.",
            "Name one clear intention and take a concrete step toward it — the resources are already in your hands."),
        TarotCard("major_02_priestess", "Верховная Жрица", "The High Priestess",
            "Внутреннее знание, интуиция и тайна: ответ приходит из тишины, а не из суеты. Тень — уход в себя и отказ действовать.",
            "Inner knowing, intuition and mystery: the answer comes from stillness, not from noise. The shadow is withdrawal and refusing to act.",
            "Не торопитесь с решениями — прислушайтесь к себе. День для наблюдения и доверия чутью.",
            "Don't rush decisions — listen inward. A day for observing and trusting your instinct."),
        TarotCard("major_03_empress", "Императрица", "The Empress",
            "Изобилие, забота, творчество и плодородие: всё растёт там, куда вложены тепло и внимание. Тень — гиперопека и потакание.",
            "Abundance, care, creativity and fertility: things grow where warmth and attention are given. The shadow is smothering and over-indulgence.",
            "Позаботьтесь о себе и близких, создайте что-то приятное. Хорошо для дома, красоты и природы.",
            "Care for yourself and those close to you, make something lovely. Good for home, beauty and nature."),
        TarotCard("major_04_emperor", "Император", "The Emperor",
            "Порядок, структура, ответственность и опора: сила в правилах и последовательности. Тень — жёсткость и потребность всё контролировать.",
            "Order, structure, responsibility and stability: strength through rules and consistency. The shadow is rigidity and the need to control everything.",
            "Наведите порядок в делах и возьмите ответственность на себя. День для дисциплины и планов.",
            "Bring order to your affairs and take responsibility. A day for discipline and planning."),
        TarotCard("major_05_hierophant", "Иерофант", "The Hierophant",
            "Традиция, наставничество и проверенные пути: опыт старших и общие ценности. Тень — догма и страх выйти за рамки.",
            "Tradition, mentorship and proven paths: the experience of elders and shared values. The shadow is dogma and fear of stepping outside the lines.",
            "Обратитесь к знанию или совету того, кто прошёл этот путь. Хорошо для учёбы и обязательств.",
            "Turn to knowledge, or to someone who has walked this path. Good for study and commitments."),
        TarotCard("major_06_lovers", "Влюблённые", "The Lovers",
            "Выбор сердца, союз и ценности: важно решить, что для вас по-настоящему дорого. Тень — колебания и уход от ответственности за выбор.",
            "A choice of the heart, union and values: it matters to decide what you truly hold dear. The shadow is wavering and dodging responsibility for the choice.",
            "Сделайте выбор в согласии с собой, а не из страха. День для отношений и честности.",
            "Choose in agreement with yourself, not out of fear. A day for relationships and honesty."),
        TarotCard("major_07_chariot", "Колесница", "The Chariot",
            "Движение к цели, воля и контроль над противоречиями: победа через собранность. Тень — упрямство и гонка напролом.",
            "Momentum, willpower and control over opposing forces: victory through focus. The shadow is stubbornness and charging ahead blindly.",
            "Соберитесь и двигайтесь к цели, удерживая направление. Уместны решимость и самоконтроль.",
            "Gather yourself and move toward the goal, holding your course. Resolve and self-control fit today."),
        TarotCard("major_08_strength", "Сила", "Strength",
            "Мягкая внутренняя сила, терпение и власть над своими порывами: побеждает спокойствие, а не давление. Тень — самоедство и подавленный гнев.",
            "Gentle inner strength, patience and mastery over one's impulses: calm wins, not force. The shadow is self-criticism and suppressed anger.",
            "Действуйте терпеливо и по-доброму, особенно к себе. Укротите раздражение — сегодня оно не помощник.",
            "Act patiently and kindly, especially toward yourself. Tame irritation — it won't help you today."),
        TarotCard("major_09_hermit", "Отшельник", "The Hermit",
            "Уединение, поиск смысла и внутренний свет: ответы внутри, вдали от шума. Тень — изоляция и бегство от людей.",
            "Solitude, a search for meaning and an inner light: answers are within, away from the noise. The shadow is isolation and fleeing from people.",
            "Выделите время побыть наедине с мыслями. День для тишины, размышления и честного взгляда внутрь.",
            "Set aside time alone with your thoughts. A day for quiet, reflection and an honest look inward."),
        TarotCard("major_10_wheel", "Колесо Фортуны", "Wheel of Fortune",
            "Перемены, циклы и поворот судьбы: что-то завершается, чтобы началось новое. Тень — пассивное ожидание милости случая.",
            "Change, cycles and a turn of fate: something ends so the new can begin. The shadow is passively waiting on luck.",
            "Примите перемены как часть движения и не цепляйтесь за старое. Ловите удачную возможность.",
            "Accept change as part of the flow and don't cling to the old. Seize the lucky opening."),
        TarotCard("major_11_justice", "Справедливость", "Justice",
            "Равновесие, честность и последствия: каждое действие получает свой ответ. Тень — холодная бухгалтерия и осуждение.",
            "Balance, honesty and consequences: every action gets its answer. The shadow is cold score-keeping and judgment.",
            "Поступайте по совести и взвешивайте решения. День для честных договорённостей и ясности.",
            "Act by your conscience and weigh your decisions. A day for fair agreements and clarity."),
        TarotCard("major_12_hanged", "Повешенный", "The Hanged Man",
            "Пауза, смена угла зрения и добровольная жертва ради нового понимания: иногда полезно отпустить контроль. Тень — застревание и роль жертвы.",
            "A pause, a shift of perspective and a willing surrender for new understanding: sometimes it helps to let go of control. The shadow is stalling and playing the victim.",
            "Остановитесь и посмотрите на ситуацию иначе. Не форсируйте — сегодня сила в принятии.",
            "Stop and look at the situation differently. Don't force it — today the strength is in acceptance."),
        TarotCard("major_13_death", "Смерть", "Death",
            "Завершение и трансформация: старое уходит, освобождая место обновлению. Это не про финал, а про переход; тень — страх отпустить.",
            "Ending and transformation: the old departs to make room for renewal. Not about a final end but a passage; the shadow is fear of letting go.",
            "Отпустите то, что отжило. День, чтобы честно закрыть страницу и дать место новому.",
            "Release what has run its course. A day to honestly close a chapter and make room for the new."),
        TarotCard("major_14_temperance", "Умеренность", "Temperance",
            "Гармония, баланс и умение соединять несоединимое: спокойное течение без крайностей. Тень — вялость и вечное откладывание.",
            "Harmony, balance and blending opposites: a calm flow without extremes. The shadow is sluggishness and endless postponing.",
            "Ищите золотую середину и не спешите. Хорошо для примирения, восстановления и меры во всём.",
            "Seek the middle way and don't hurry. Good for reconciliation, recovery and moderation in all things."),
        TarotCard("major_15_devil", "Дьявол", "The Devil",
            "Привязанности, зависимости и иллюзия несвободы: цепи часто держатся на нашем согласии. Тень — оправдание того, что вредит.",
            "Attachments, dependencies and the illusion of bondage: the chains often hold only by our consent. The shadow is justifying what harms you.",
            "Честно посмотрите, что вас держит и что вы сами выбираете терпеть. День осознать свои соблазны.",
            "Look honestly at what binds you and what you choose to put up with. A day to see your own temptations."),
        TarotCard("major_16_tower", "Башня", "The Tower",
            "Внезапное разрушение ложного и освобождение через потрясение: рушится то, что стояло на неверном основании. Тень — цепляние за обломки.",
            "The sudden collapse of the false and freedom through upheaval: what stood on a wrong foundation falls. The shadow is clinging to the rubble.",
            "Не держитесь за рушащееся — за сломом откроется правда. Будьте гибки к неожиданным переменам.",
            "Don't hold on to what's collapsing — truth opens behind the break. Stay flexible with sudden change."),
        TarotCard("major_17_star", "Звезда", "The Star",
            "Надежда, вдохновение и исцеление: после бури приходит тихий свет и вера в лучшее. Тень — уход в мечты вместо шагов.",
            "Hope, inspiration and healing: after the storm comes a quiet light and faith in what's ahead. The shadow is drifting into dreams instead of steps.",
            "Позвольте себе надеяться и мечтать. День для восстановления, творчества и веры в свой путь.",
            "Allow yourself to hope and dream. A day for recovery, creativity and faith in your path."),
        TarotCard("major_18_moon", "Луна", "The Moon",
            "Иллюзии, тревоги и подсознание: не всё то, чем кажется; страхи преувеличивают тени. Тень — самообман и блуждание в потёмках.",
            "Illusion, anxiety and the subconscious: not all is as it seems; fears magnify the shadows. The shadow is self-deception and wandering in the dark.",
            "Не принимайте важных решений на эмоциях и не верьте всем тревогам. Доверьтесь интуиции, а не панике.",
            "Don't make big decisions on emotion, and don't believe every worry. Trust intuition, not panic."),
        TarotCard("major_19_sun", "Солнце", "The Sun",
            "Радость, ясность, успех и жизненная сила: всё выходит на свет и становится простым. Тень — самоуверенность и показная бравада.",
            "Joy, clarity, success and vitality: everything comes into the light and turns simple. The shadow is overconfidence and showy bravado.",
            "Радуйтесь и делитесь теплом — день благоприятен почти во всём. Хорошее время быть на виду.",
            "Rejoice and share your warmth — the day favors almost everything. A good time to be seen."),
        TarotCard("major_20_judgement", "Суд", "Judgement",
            "Пробуждение, переоценка и зов к обновлению: пора подвести итог и услышать своё призвание. Тень — суровый суд над собой.",
            "Awakening, reappraisal and a call to renewal: time to take stock and hear your calling. The shadow is harsh self-judgment.",
            "Оцените пройденное честно и ответьте на внутренний зов. День прощения и нового старта.",
            "Weigh the path so far honestly and answer the inner call. A day of forgiveness and a fresh start."),
        TarotCard("major_21_world", "Мир", "The World",
            "Завершение цикла, целостность и достижение: пазл сложился, путь пройден. Тень — страх закончить и шагнуть в новый круг.",
            "The close of a cycle, wholeness and accomplishment: the pieces fit, the journey is complete. The shadow is fearing the end and the next circle.",
            "Отпразднуйте достигнутое и почувствуйте полноту. Хорошо завершать дела и подводить итоги.",
            "Celebrate what you've reached and feel the fullness. Good for finishing things and taking stock."),

        // --- Жезлы (огонь: воля, действие, энергия) ---
        TarotCard("wands_01", "Туз Жезлов", "Ace of Wands",
            "Искра, вдохновение и импульс к действию: новая энергия и желание творить. Тень — вспышка, что гаснет без шага.",
            "A spark, inspiration and the urge to act: new energy and the desire to create. The shadow is a flash that fades without a step.",
            "Хватайтесь за идею, пока горит — сделайте первый шаг. День энтузиазма и старта.",
            "Grab the idea while it burns — take the first step. A day of enthusiasm and beginnings."),
        TarotCard("wands_02", "Двойка Жезлов", "Two of Wands",
            "Планирование, выбор направления и взгляд вдаль: мир в руках, но нужно решить, куда идти. Тень — вечное «потом» вместо решения.",
            "Planning, choosing a direction and looking far: the world is in your hands, but you must decide where to go. The shadow is endless 'later' instead of a decision.",
            "Наметьте цель и горизонт. Хорошо строить планы и решаться на большее.",
            "Set a goal and a horizon. Good for making plans and daring to reach further."),
        TarotCard("wands_03", "Тройка Жезлов", "Three of Wands",
            "Расширение, первые результаты и ожидание: корабли отправлены, впереди возможности. Тень — нетерпение и сомнение в пути.",
            "Expansion, first results and anticipation: the ships are out, opportunities lie ahead. The shadow is impatience and doubting the path.",
            "Смотрите шире и не бойтесь выходить за привычные границы. День роста и перспектив.",
            "Look wider and don't fear stepping past familiar limits. A day of growth and prospects."),
        TarotCard("wands_04", "Четвёрка Жезлов", "Four of Wands",
            "Праздник, стабильность и радость дома: веха, которую хочется отметить. Тень — тревога, что мешает просто порадоваться.",
            "Celebration, stability and the joy of home: a milestone worth marking. The shadow is worry that won't let you simply rejoice.",
            "Порадуйтесь достигнутому в кругу близких. Хорошо для встреч, дома и благодарности.",
            "Celebrate what you've reached among loved ones. Good for gatherings, home and gratitude."),
        TarotCard("wands_05", "Пятёрка Жезлов", "Five of Wands",
            "Соперничество, споры и суета: много энергии, но она сталкивается лбами. Тень — конфликт ради конфликта.",
            "Rivalry, arguments and commotion: plenty of energy, but it collides head-on. The shadow is conflict for its own sake.",
            "Не втягивайтесь в пустые конфликты — направьте пыл в дело. День разногласий, держите фокус.",
            "Don't get pulled into empty conflicts — channel the heat into work. A day of friction; keep your focus."),
        TarotCard("wands_06", "Шестёрка Жезлов", "Six of Wands",
            "Победа, признание и заслуженный успех: усилия замечены. Тень — зависимость от чужой похвалы.",
            "Victory, recognition and well-earned success: your efforts are noticed. The shadow is depending on others' praise.",
            "Примите похвалу и идите вперёд с уверенностью. День достижений и хороших новостей.",
            "Accept the praise and move forward with confidence. A day of achievements and good news."),
        TarotCard("wands_07", "Семёрка Жезлов", "Seven of Wands",
            "Отстаивание позиции, вызов и стойкость: нужно защитить своё. Тень — оборона там, где никто не нападает.",
            "Standing your ground, challenge and resilience: you need to defend what's yours. The shadow is defending against an attack that isn't there.",
            "Держите свою линию, если уверены в правоте. День требует смелости и упорства.",
            "Hold your line if you're sure you're right. The day calls for courage and persistence."),
        TarotCard("wands_08", "Восьмёрка Жезлов", "Eight of Wands",
            "Скорость, новости и стремительное движение: события набирают темп. Тень — спешка без разбора.",
            "Speed, news and swift movement: events pick up pace. The shadow is haste without discernment.",
            "Действуйте быстро и не откладывайте — момент летит. Ждите новостей и сообщений.",
            "Act quickly and don't delay — the moment is flying. Expect news and messages."),
        TarotCard("wands_09", "Девятка Жезлов", "Nine of Wands",
            "Стойкость на последнем рубеже, усталость и настороженность: почти дошли, но силы на исходе. Тень — оборона из старых обид.",
            "Endurance at the last stand, fatigue and wariness: you're almost there, but running low. The shadow is guarding out of old wounds.",
            "Не сдавайтесь у самой цели, но берегите ресурс. День упорства, второе дыхание рядом.",
            "Don't give up right at the goal, but spare your reserves. A day of persistence; a second wind is near."),
        TarotCard("wands_10", "Десятка Жезлов", "Ten of Wands",
            "Перегруз, ноша и ответственность сверх меры: взвалили слишком много. Тень — привычка тащить всё в одиночку.",
            "Overload, burden and responsibility beyond measure: you've taken on too much. The shadow is the habit of carrying it all alone.",
            "Разгрузите себя и делегируйте лишнее. Не тащите всё в одиночку — день о границах нагрузки.",
            "Lighten your load and delegate the excess. Don't carry it all yourself — a day about the limits of your load."),
        TarotCard("wands_11", "Паж Жезлов", "Page of Wands",
            "Любопытство, вдохновение и весть о начинании: юный задор и жажда нового. Тень — разбросанность и незаконченность.",
            "Curiosity, inspiration and word of a new venture: youthful spark and a hunger for the new. The shadow is scattering and leaving things unfinished.",
            "Пробуйте, экспериментируйте, загорайтесь идеей. День открытости и лёгкого авантюризма.",
            "Try, experiment, catch fire from an idea. A day of openness and light adventure."),
        TarotCard("wands_12", "Рыцарь Жезлов", "Knight of Wands",
            "Порыв, страсть и стремительное действие: энергия рвётся вперёд. Тень — импульсивность и брошенное на полпути.",
            "Impulse, passion and swift action: energy surges forward. The shadow is impulsiveness and things abandoned halfway.",
            "Действуйте смело, но не растрачивайте пыл впустую. День инициативы и движения.",
            "Act boldly, but don't burn your fire for nothing. A day of initiative and movement."),
        TarotCard("wands_13", "Королева Жезлов", "Queen of Wands",
            "Уверенность, харизма и тёплая сила: умение вдохновлять и вести за собой. Тень — ревность и потребность быть в центре.",
            "Confidence, charisma and warm strength: the gift of inspiring and leading. The shadow is jealousy and needing to be the center.",
            "Будьте собой ярко и щедро, зажигайте других. День личного магнетизма и творчества.",
            "Be yourself brightly and generously, light up others. A day of personal magnetism and creativity."),
        TarotCard("wands_14", "Король Жезлов", "King of Wands",
            "Лидерство, видение и зрелая воля: способность вести к большой цели. Тень — деспотизм и нетерпимость к чужому темпу.",
            "Leadership, vision and mature will: the ability to lead toward a big goal. The shadow is tyranny and impatience with others' pace.",
            "Берите инициативу и мыслите масштабно. День для смелых решений и лидерства.",
            "Take the initiative and think big. A day for bold decisions and leadership."),

        // --- Кубки (вода: чувства, отношения, интуиция) ---
        TarotCard("cups_01", "Туз Кубков", "Ace of Cups",
            "Новое чувство, открытое сердце и источник любви: эмоциональное начало. Тень — страх впустить и снова уязвиться.",
            "A new feeling, an open heart and a source of love: an emotional beginning. The shadow is fear of letting it in and being hurt again.",
            "Откройтесь чувствам и добру — своим и чужим. День нежности, принятия и тёплых связей.",
            "Open to feeling and kindness — yours and others'. A day of tenderness, acceptance and warm bonds."),
        TarotCard("cups_02", "Двойка Кубков", "Two of Cups",
            "Союз, взаимность и притяжение: встреча двух на равных. Тень — идеализация и слияние в ущерб себе.",
            "Union, mutuality and attraction: a meeting of two as equals. The shadow is idealizing and merging at your own expense.",
            "Цените взаимность и стройте мосты. Хорошо для отношений, партнёрства и примирения.",
            "Value mutuality and build bridges. Good for relationships, partnership and reconciliation."),
        TarotCard("cups_03", "Тройка Кубков", "Three of Cups",
            "Дружба, радость и общий праздник: тепло круга близких. Тень — уход в веселье от того, что стоит решить.",
            "Friendship, joy and shared celebration: the warmth of a close circle. The shadow is escaping into fun from what needs facing.",
            "Проведите время с теми, кто дорог. День встреч, поддержки и совместной радости.",
            "Spend time with those dear to you. A day of gatherings, support and shared joy."),
        TarotCard("cups_04", "Четвёрка Кубков", "Four of Cups",
            "Апатия, пресыщение и взгляд мимо возможностей: скука застилает хорошее. Тень — обесценивание того, что есть.",
            "Apathy, satiety and looking past opportunities: boredom veils the good. The shadow is dismissing what you already have.",
            "Оглянитесь — рядом есть то, что вы не замечаете. Стряхните хандру и откройтесь новому.",
            "Look around — something near you goes unnoticed. Shake off the gloom and open to the new."),
        TarotCard("cups_05", "Пятёрка Кубков", "Five of Cups",
            "Сожаление, потеря и печаль о пролитом — но не всё утрачено. Тень — взгляд только на разбитое.",
            "Regret, loss and grief over what's spilled — yet not all is lost. The shadow is looking only at what's broken.",
            "Погрустив, обернитесь: часть опор ещё цела. День принять утрату и увидеть оставшееся.",
            "After grieving, turn around: some supports still stand. A day to accept the loss and see what remains."),
        TarotCard("cups_06", "Шестёрка Кубков", "Six of Cups",
            "Ностальгия, доброта и тёплые воспоминания: свет прошлого и невинность. Тень — жизнь во «вчера» вместо сегодня.",
            "Nostalgia, kindness and warm memories: the light of the past and innocence. The shadow is living in 'yesterday' instead of today.",
            "Вспомните доброе и подарите заботу без счёта. Хорошо для семьи, детей и старых связей.",
            "Recall the good and give care freely. Good for family, children and old bonds."),
        TarotCard("cups_07", "Семёрка Кубков", "Seven of Cups",
            "Мечты, иллюзии и обилие соблазнов: много вариантов, но не все реальны. Тень — паралич от выбора и грёзы вместо дела.",
            "Dreams, illusions and a wealth of temptations: many options, not all of them real. The shadow is choice paralysis and daydreaming instead of doing.",
            "Отделите настоящее желание от фантазии и выберите одно. День не распыляться на миражи.",
            "Separate real desire from fantasy and pick one. A day not to scatter yourself on mirages."),
        TarotCard("cups_08", "Восьмёрка Кубков", "Eight of Cups",
            "Уход ради большего, поиск смысла и расставание с тем, что не наполняет. Тень — бегство по кругу вместо решения.",
            "Walking away for something greater, a search for meaning and parting with what doesn't fulfill. The shadow is fleeing in circles instead of resolving.",
            "Оставьте то, что исчерпано, и идите за глубиной. День честного «мне нужно другое».",
            "Leave what's exhausted and go toward depth. A day for an honest 'I need something else.'"),
        TarotCard("cups_09", "Девятка Кубков", "Nine of Cups",
            "Удовлетворение, исполнение желания и душевный уют: карта сбывшегося. Тень — довольство собой и остановка в росте.",
            "Contentment, a wish fulfilled and inner comfort: the card of things coming true. The shadow is complacency and stalling in growth.",
            "Позвольте себе удовольствие и благодарность. Хороший день радоваться тому, что есть.",
            "Allow yourself pleasure and gratitude. A good day to enjoy what you have."),
        TarotCard("cups_10", "Десятка Кубков", "Ten of Cups",
            "Гармония, семья и полнота счастья: эмоциональное изобилие. Тень — страх, что идиллия хрупка.",
            "Harmony, family and the fullness of happiness: emotional abundance. The shadow is fearing the idyll is fragile.",
            "Цените близость и общий лад. День тепла, дома и благодарности за отношения.",
            "Value closeness and harmony. A day of warmth, home and gratitude for your relationships."),
        TarotCard("cups_11", "Паж Кубков", "Page of Cups",
            "Нежность, творческий импульс и добрая весть чувств: наивная искренность. Тень — обидчивость и уход в фантазии.",
            "Tenderness, a creative impulse and good news of the heart: naive sincerity. The shadow is touchiness and retreat into fantasy.",
            "Прислушайтесь к сердцу и не стыдитесь мягкости. День вдохновения и тёплых сообщений.",
            "Listen to your heart and don't be ashamed of gentleness. A day of inspiration and warm messages."),
        TarotCard("cups_12", "Рыцарь Кубков", "Knight of Cups",
            "Романтика, идеал и движение сердцем: предложение или порыв чувств. Тень — обещания, которые трудно сдержать.",
            "Romance, an ideal and moving by the heart: an offer or a surge of feeling. The shadow is promises hard to keep.",
            "Следуйте за красотой и добрым порывом. День для романтики, искусства и примирения.",
            "Follow beauty and a kind impulse. A day for romance, art and reconciliation."),
        TarotCard("cups_13", "Королева Кубков", "Queen of Cups",
            "Чуткость, сострадание и эмоциональная мудрость: умение чувствовать и поддерживать. Тень — растворение в чужих чувствах.",
            "Sensitivity, compassion and emotional wisdom: the gift of feeling and supporting. The shadow is dissolving into others' emotions.",
            "Будьте внимательны к чувствам — своим и чужим. День заботы, эмпатии и интуиции.",
            "Be attentive to feelings — yours and others'. A day of care, empathy and intuition."),
        TarotCard("cups_14", "Король Кубков", "King of Cups",
            "Зрелость чувств, спокойствие и владение эмоциями: тёплая, но устойчивая сила. Тень — подавление чувств под маской покоя.",
            "Emotional maturity, calm and mastery of feeling: a warm yet steady strength. The shadow is suppressing emotion behind a mask of calm.",
            "Сохраняйте душевное равновесие и поддержите других. День дипломатии и внутреннего покоя.",
            "Keep your inner balance and support others. A day of diplomacy and inner peace."),

        // --- Мечи (воздух: ум, слова, решения) ---
        TarotCard("swords_01", "Туз Мечей", "Ace of Swords",
            "Ясность, правда и прорыв мысли: ум рассекает туман. Тень — резкость и правда, сказанная как оружие.",
            "Clarity, truth and a breakthrough of thought: the mind cuts through the fog. The shadow is sharpness and truth used as a weapon.",
            "Назовите вещи своими именами и примите ясное решение. День истины и точных формулировок.",
            "Call things by their names and make a clear decision. A day of truth and precise wording."),
        TarotCard("swords_02", "Двойка Мечей", "Two of Swords",
            "Нерешительность, равновесие на грани и закрытые глаза: выбор откладывается. Тень — избегание, что копит напряжение.",
            "Indecision, a knife-edge balance and closed eyes: the choice is postponed. The shadow is avoidance that builds tension.",
            "Снимите повязку и посмотрите на факты — решение придётся принять. День перестать избегать.",
            "Take off the blindfold and look at the facts — the choice must be made. A day to stop avoiding."),
        TarotCard("swords_03", "Тройка Мечей", "Three of Swords",
            "Боль, разочарование и горькая правда: сердце ранено словом или разрывом. Тень — жизнь в обиде и растравление раны.",
            "Pain, disappointment and a bitter truth: the heart is wounded by a word or a break. The shadow is dwelling in hurt and reopening the wound.",
            "Позвольте себе прожить боль, не растравляя её. День принять и начать исцеление.",
            "Let yourself feel the pain without picking at it. A day to accept and begin healing."),
        TarotCard("swords_04", "Четвёрка Мечей", "Four of Swords",
            "Отдых, пауза и восстановление: уму нужна тишина. Тень — застой, если пауза затянулась.",
            "Rest, a pause and recovery: the mind needs quiet. The shadow is stagnation if the pause drags on.",
            "Дайте себе передышку и не решайте всё сразу. День покоя, сна и восстановления сил.",
            "Give yourself a breather and don't decide everything at once. A day of rest, sleep and recovery."),
        TarotCard("swords_05", "Пятёрка Мечей", "Five of Swords",
            "Конфликт, цена победы и уязвлённое самолюбие: выиграть можно, но какой ценой. Тень — правота дороже отношений.",
            "Conflict, the cost of winning and wounded pride: you can win, but at what price. The shadow is valuing being right over the relationship.",
            "Не доказывайте правоту любой ценой — иные победы дороже потерь. День выбирать мир.",
            "Don't prove your point at any cost — some wins cost more than they're worth. A day to choose peace."),
        TarotCard("swords_06", "Шестёрка Мечей", "Six of Swords",
            "Переход, отдаление от бури и движение к спокойствию: постепенное улучшение. Тень — уносить старые тревоги с собой.",
            "Transition, moving away from the storm toward calm: gradual improvement. The shadow is carrying old worries along.",
            "Двигайтесь к более спокойным водам, оставляя тревоги позади. День перемен к лучшему.",
            "Move toward calmer waters, leaving worries behind. A day of change for the better."),
        TarotCard("swords_07", "Семёрка Мечей", "Seven of Swords",
            "Хитрость, уловка и действие в обход: кто-то (или вы) играет не в открытую. Тень — самообман и мелкая нечестность.",
            "Cunning, a ploy and going around the front: someone — or you — isn't playing openly. The shadow is self-deception and petty dishonesty.",
            "Действуйте честно и проверьте, где вами лукавят. День осторожности и ясной стратегии.",
            "Act honestly and check where you're being played. A day of caution and a clear strategy."),
        TarotCard("swords_08", "Восьмёрка Мечей", "Eight of Swords",
            "Ощущение ловушки, скованность мыслью и мнимая безвыходность: путы часто в голове. Тень — согласие на роль пленника.",
            "A sense of being trapped, bound by thought and false hopelessness: the ties are often in the mind. The shadow is agreeing to the role of prisoner.",
            "Оглядитесь: выход есть, страх его прячет. День снять с себя надуманные ограничения.",
            "Look around: there's a way out, fear hides it. A day to shed imagined limits."),
        TarotCard("swords_09", "Девятка Мечей", "Nine of Swords",
            "Тревога, бессонница и ночные страхи: ум преувеличивает беду. Тень — вера тревоге как факту.",
            "Anxiety, sleeplessness and night fears: the mind blows trouble out of proportion. The shadow is trusting worry as if it were fact.",
            "Не верьте тревоге как факту — при свете дня всё меньше. День бережности к себе.",
            "Don't take worry as fact — by daylight it shrinks. A day of gentleness toward yourself."),
        TarotCard("swords_10", "Десятка Мечей", "Ten of Swords",
            "Дно, завершение тяжёлого и конец мучительного: хуже уже не будет — начинается рассвет. Тень — драматизация и роль жертвы.",
            "Rock bottom, the end of the hard and the close of the painful: it won't get worse — dawn is coming. The shadow is drama and the victim role.",
            "Признайте окончание и не оживляйте отжившее. День отпустить и начать заново.",
            "Acknowledge the ending and don't revive the dead. A day to let go and begin again."),
        TarotCard("swords_11", "Паж Мечей", "Page of Swords",
            "Любознательность, бдительность и острый ум: жажда узнать и понять. Тень — колкость и суждение свысока.",
            "Curiosity, alertness and a sharp mind: a hunger to learn and understand. The shadow is a sharp tongue and judging from above.",
            "Задавайте вопросы и проверяйте факты. День учиться, наблюдать и говорить точно.",
            "Ask questions and check the facts. A day to learn, observe and speak precisely."),
        TarotCard("swords_12", "Рыцарь Мечей", "Knight of Swords",
            "Напор, прямота и стремительность мысли: идея рвётся в бой. Тень — резать сплеча и ранить словом.",
            "Drive, directness and swiftness of thought: the idea charges into battle. The shadow is cutting rashly and wounding with words.",
            "Действуйте решительно, но не рубите сплеча. День смелых слов — следите за тактом.",
            "Act decisively, but don't strike blindly. A day of bold words — mind your tact."),
        TarotCard("swords_13", "Королева Мечей", "Queen of Swords",
            "Ясность ума, честность и независимость: трезвый взгляд без иллюзий. Тень — холодность и отстранённость.",
            "Clarity of mind, honesty and independence: a sober view without illusions. The shadow is coldness and detachment.",
            "Мыслите чётко и говорите правду по-доброму. День здравого смысла и границ.",
            "Think clearly and tell the truth kindly. A day of common sense and boundaries."),
        TarotCard("swords_14", "Король Мечей", "King of Swords",
            "Интеллект, принципы и справедливое решение: власть разума и слова. Тень — сухая логика без сердца.",
            "Intellect, principles and a fair judgment: the authority of mind and word. The shadow is dry logic without heart.",
            "Решайте на основе фактов и логики, беспристрастно. День для анализа и честных вердиктов.",
            "Decide on facts and logic, impartially. A day for analysis and fair verdicts."),

        // --- Пентакли (земля: дело, деньги, тело) ---
        TarotCard("pents_01", "Туз Пентаклей", "Ace of Pentacles",
            "Новая возможность, ресурс и прочное начало: семя достатка и стабильности. Тень — жажда гарантий вместо шага.",
            "A new opportunity, a resource and a solid start: a seed of prosperity and stability. The shadow is craving guarantees instead of a step.",
            "Заложите основу дела или привычки — вложение окупится. День практичного старта.",
            "Lay the foundation of a venture or habit — the investment pays off. A day for a practical start."),
        TarotCard("pents_02", "Двойка Пентаклей", "Two of Pentacles",
            "Жонглирование делами, гибкость и баланс ресурсов: много всего сразу. Тень — суета и потеря главного.",
            "Juggling tasks, flexibility and balancing resources: many things at once. The shadow is busyness and losing sight of what matters.",
            "Распределите силы и не хватайтесь за всё разом. День гибкости и расстановки приоритетов.",
            "Spread your energy and don't grab everything at once. A day of flexibility and setting priorities."),
        TarotCard("pents_03", "Тройка Пентаклей", "Three of Pentacles",
            "Мастерство, сотрудничество и первые плоды труда: дело складывается вместе. Тень — тянуть одеяло на себя.",
            "Craft, collaboration and the first fruits of work: it comes together as a team. The shadow is pulling the credit your way.",
            "Работайте в связке и учитесь у умелых. День командной работы и роста навыка.",
            "Work in tandem and learn from the skilled. A day of teamwork and growing your craft."),
        TarotCard("pents_04", "Четвёрка Пентаклей", "Four of Pentacles",
            "Сбережение, контроль и страх потерять: держим крепко, порой слишком. Тень — скупость и зажим.",
            "Saving, control and fear of loss: we hold on tight, sometimes too tight. The shadow is stinginess and clenching.",
            "Берегите ресурсы, но не превращайте это в зажим. День о разумной мере в контроле.",
            "Guard your resources, but don't let it turn into a clench. A day about a sensible measure of control."),
        TarotCard("pents_05", "Пятёрка Пентаклей", "Five of Pentacles",
            "Нужда, трудный период и чувство отверженности — но помощь ближе, чем кажется. Тень — гордость, что мешает попросить.",
            "Hardship, a lean time and a sense of being left out — yet help is nearer than it seems. The shadow is pride that stops you from asking.",
            "Не стесняйтесь попросить поддержки — вы не одни. День пережить и найти опору.",
            "Don't hesitate to ask for support — you're not alone. A day to get through and find footing."),
        TarotCard("pents_06", "Шестёрка Пентаклей", "Six of Pentacles",
            "Щедрость, обмен и справедливое распределение: дать и получить по совести. Тень — власть через подачку и зависимость.",
            "Generosity, exchange and fair distribution: giving and receiving in good faith. The shadow is power through handouts and dependency.",
            "Поделитесь тем, чего в достатке, или примите помощь без вины. День баланса в обмене.",
            "Share what you have plenty of, or accept help without guilt. A day of balance in giving and taking."),
        TarotCard("pents_07", "Семёрка Пентаклей", "Seven of Pentacles",
            "Терпение, оценка вложенного и ожидание урожая: плоды зреют не сразу. Тень — сомнение, что бросает дело на полпути.",
            "Patience, assessing what you've invested and awaiting the harvest: fruit doesn't ripen at once. The shadow is doubt that quits halfway.",
            "Оцените, что уже выросло, и наберитесь терпения. День вдумчивой паузы в делах.",
            "Assess what has already grown and be patient. A day for a thoughtful pause in your work."),
        TarotCard("pents_08", "Восьмёрка Пентаклей", "Eight of Pentacles",
            "Труд, оттачивание мастерства и внимание к деталям: рост через дело. Тень — перфекционизм и работа ради работы.",
            "Diligence, honing your craft and attention to detail: growth through the work itself. The shadow is perfectionism and work for its own sake.",
            "Погрузитесь в работу и доведите до качества. День усердия и малых улучшений.",
            "Dive into the work and bring it to quality. A day of diligence and small improvements."),
        TarotCard("pents_09", "Девятка Пентаклей", "Nine of Pentacles",
            "Достаток, самостоятельность и заслуженный комфорт: плоды своих трудов. Тень — одиночество за красивым фасадом.",
            "Prosperity, independence and well-earned comfort: the fruits of your own labor. The shadow is loneliness behind a fine facade.",
            "Насладитесь тем, что заработали сами. День самодостаточности и удовольствия от результата.",
            "Enjoy what you've earned yourself. A day of self-sufficiency and pleasure in the result."),
        TarotCard("pents_10", "Десятка Пентаклей", "Ten of Pentacles",
            "Стабильность, наследие и семейное благополучие: прочный фундамент надолго. Тень — жизнь по инерции ради «положено».",
            "Stability, legacy and family well-being: a solid foundation for the long run. The shadow is coasting by inertia for the sake of 'what's expected.'",
            "Думайте вдолгую и укрепляйте основу. День о семье, доме и надёжных вложениях.",
            "Think long-term and strengthen the foundation. A day about family, home and reliable investments."),
        TarotCard("pents_11", "Паж Пентаклей", "Page of Pentacles",
            "Учёба, замысел дела и практическое любопытство: первый интерес к результату. Тень — планы, что не идут дальше слов.",
            "Study, a plan for a venture and practical curiosity: a first interest in results. The shadow is plans that never get past words.",
            "Начните учиться новому или планировать доход. День прилежания и конкретных шагов.",
            "Start learning something new or planning income. A day of diligence and concrete steps."),
        TarotCard("pents_12", "Рыцарь Пентаклей", "Knight of Pentacles",
            "Надёжность, методичность и терпеливое движение: медленно, но верно. Тень — рутина, что переходит в застой.",
            "Reliability, method and patient progress: slow but sure. The shadow is routine that slides into stagnation.",
            "Делайте рутину без спешки — постоянство приведёт к цели. День дисциплины и порядка.",
            "Do the routine without rushing — steadiness gets you there. A day of discipline and order."),
        TarotCard("pents_13", "Королева Пентаклей", "Queen of Pentacles",
            "Забота, практичность и уют: умение обустроить жизнь и поддержать. Тень — забыть о себе, заботясь обо всех.",
            "Care, practicality and comfort: the gift of arranging life and supporting others. The shadow is forgetting yourself while tending to everyone.",
            "Позаботьтесь о теле, доме и близких по-хозяйски. День практичной доброты.",
            "Care for your body, home and loved ones in a grounded way. A day of practical kindness."),
        TarotCard("pents_14", "Король Пентаклей", "King of Pentacles",
            "Достаток, надёжность и деловая зрелость: прочный результат и щедрая стабильность. Тень — власть денег и упор на статус.",
            "Prosperity, reliability and business maturity: a solid result and generous stability. The shadow is the power of money and a focus on status.",
            "Управляйте ресурсами уверенно и великодушно. День для финансов, дела и надёжных решений.",
            "Manage resources with confidence and generosity. A day for finances, work and sound decisions."),
    )

    init {
        require(cards.size == 78) { "В колоде должно быть 78 карт, а не ${cards.size}" }
    }

    fun byId(id: String): TarotCard? = cards.firstOrNull { it.id == id }

    /** n различных случайных карт — для выбора «трёх рубашек» и для раскладов. */
    fun draw(n: Int): List<TarotCard> = cards.shuffled().take(n)
}
