package ru.astrosmap.app.ui.tarot

import ru.astrosmap.app.ui.AstroLabels

/**
 * Колода Райдера—Уэйта, 78 карт. Только прямое положение — одна трактовка на карту.
 *
 * id совпадает с именем файла в assets/tarot/<id>.webp. Тексты авторские, двуязычные:
 * meaning — суть аркана (с оттенком роста/тени), advice — как применить в течение дня.
 * name/meaning/advice выбираются по языку приложения (AstroLabels.isRu()).
 */
data class TarotCard(
    val id: String,
    val nameRu: String,
    val nameEn: String,
    val meaningRu: String,
    val meaningEn: String,
    val adviceRu: String,
    val adviceEn: String,
) {
    val name: String get() = if (AstroLabels.isRu()) nameRu else nameEn
    val meaning: String get() = if (AstroLabels.isRu()) meaningRu else meaningEn
    val advice: String get() = if (AstroLabels.isRu()) adviceRu else adviceEn
}

object TarotDeck {

    val cards: List<TarotCard> = listOf(
        // --- Старшие арканы ---
        TarotCard("major_00_fool", "Шут", "The Fool",
            "Порог нового и чистая вера в жизнь. Шут делает шаг налегке, без груза вчерашних правил — в нём живёт спонтанность, любопытство и доверие пути. Проявляется как начало дела, переезда, романа или самой судьбы. Оборотная сторона — наивность и привычка прыгать, не глядя под ноги.",
            "The threshold of the new and a pure trust in life. The Fool steps out unburdened, free of yesterday's rules, carrying spontaneity, curiosity and faith in the road. It shows up as the start of a venture, a move, a romance, of the journey itself. Its harder edge is naivety and a habit of leaping without looking down.",
            "Сделайте один искренний шаг в неизвестность — небольшой, но настоящий. Сохраните лёгкость и любопытство, но всё же гляньте, куда ставите ногу.",
            "Take one honest step into the unknown, small but real. Keep the lightness and curiosity, yet still glance at where your foot lands."),
        TarotCard("major_01_magician", "Маг", "The Magician",
            "Собранная воля, которая превращает замысел в дело. Маг соединяет небо и землю: у него под рукой все четыре стихии, и всё нужное уже есть. Это про личную силу, фокус и мастерство в моменте, когда вы становитесь причиной, а не следствием. Осторожность нужна с соблазном пускать этот дар на манипуляцию и распылять его на мелочи.",
            "Focused will that turns an idea into a deed. The Magician links heaven and earth: all four elements sit within reach, and everything needed is already here. This is personal power, concentration and skill in the moment you become the cause rather than the effect. The caution is the pull to bend the gift toward manipulation, or fritter it away on trifles.",
            "Назовите одно ясное намерение и сделайте по нему конкретный шаг — инструменты уже в ваших руках.",
            "Name one clear intention and take a concrete step toward it — the tools are already in your hands."),
        TarotCard("major_02_priestess", "Верховная Жрица", "The High Priestess",
            "Тихое внутреннее знание, что приходит раньше слов. Жрица сидит между двух колонн, у завесы, за которой скрыто ещё не проявленное; её стихия — интуиция, сны, паузы и то, что чувствуешь кожей. Часто говорит: ответ уже есть, просто он созревает в тишине. Ловушка — уйти в наблюдение так глубоко, что перестаёшь действовать вовсе.",
            "A quiet inner knowing that arrives before words. The Priestess sits between two pillars at a veil that hides what has not yet taken form; her element is intuition, dreams, pauses and what the skin senses. She often says the answer is already there, simply ripening in the stillness. The trap is drifting so far into watching that you stop acting at all.",
            "Не торопите решение — дайте ему дозреть и прислушайтесь к первому тихому отклику внутри. Хороший день наблюдать и вести записи.",
            "Don't rush the decision — let it ripen and listen for the first quiet response within. A good day to observe and keep notes."),
        TarotCard("major_03_empress", "Императрица", "The Empress",
            "Плодородие, тепло и щедрость живой природы. Императрица растит всё, к чему прикасается: отношения, замыслы, тело, дом. Её энергия чувственная и питающая — она про заботу, красоту, творчество и удовольствие быть в мире. Слишком много опеки, и забота превращается в удушье или в потворство, за которым теряется рост.",
            "Fertility, warmth and the generosity of living nature. The Empress grows whatever she touches: bonds, ideas, the body, the home. Her energy is sensual and nourishing — care, beauty, creativity and the pleasure of simply being alive. Give too much, though, and tending turns into smothering, or an indulgence that quietly stalls growth.",
            "Вложите тепло в то, что хотите вырастить, и позвольте себе удовольствие без вины. День для дома, красоты и природы.",
            "Pour warmth into what you want to grow, and let yourself enjoy without guilt. A day for home, beauty and nature."),
        TarotCard("major_04_emperor", "Император", "The Emperor",
            "Опора, порядок и ответственность зрелого хозяина. Император строит рамки, в которых жизнь становится устойчивой: правила, структура, чёткие границы, слово, которое держат. Это отцовская сила, дающая защиту и форму. Когда порядок каменеет, он оборачивается жёсткостью и желанием держать под контролем каждую мелочь.",
            "Foundation, order and the responsibility of a seasoned steward. The Emperor builds the framework that makes life steady: rules, structure, firm boundaries, a word that holds. This is fatherly strength that gives protection and shape. When order hardens, it curdles into rigidity and a need to control every last detail.",
            "Наведите порядок в делах и возьмите ответственность на себя, а не ждите, что решат другие. День дисциплины и ясного плана.",
            "Bring order to your affairs and take the responsibility yourself instead of waiting on others. A day for discipline and a clear plan."),
        TarotCard("major_05_hierophant", "Иерофант", "The Hierophant",
            "Мост между человеком и большим смыслом — традиция, наставник, проверенный путь. Иерофант хранит общие ценности, посвящает, обучает, связывает поколения. Он говорит о пользе опыта тех, кто прошёл дорогу раньше, о ритуалах и принадлежности. Тень аркана — догма и страх сделать шаг за пределы одобренного.",
            "A bridge between a person and a larger meaning — tradition, a mentor, a proven road. The Hierophant keeps shared values, initiates, teaches, binds the generations. He speaks of the worth in those who walked the path before you, of ritual and belonging. The arcanum's shadow is dogma and the fear of stepping past what has been approved.",
            "Обратитесь к знанию или к тому, кто уже прошёл этот путь, но оставьте право на свой вывод. Хорошо для учёбы и серьёзных обязательств.",
            "Turn to knowledge or to someone who has walked this path, while keeping the right to your own conclusion. Good for study and serious commitments."),
        TarotCard("major_06_lovers", "Влюблённые", "The Lovers",
            "Встреча, притяжение и выбор сердца. Влюблённые — не только про любовь между двумя, но и про верность себе: что для вас по-настоящему ценно и с чем вы готовы соединиться. Здесь рождается союз и решается, чему сказать да. Уязвимое место — метания и попытка увильнуть от ответственности за собственный выбор.",
            "Meeting, attraction and a choice of the heart. The Lovers is not only love between two people but fidelity to yourself: what you truly value and what you are ready to join with. Here a union is born and a yes gets decided. The tender spot is wavering and the wish to slip out from under the weight of your own choice.",
            "Сделайте выбор в согласии с собой, а не из страха потерять или обидеть. День для отношений и предельной честности.",
            "Choose in agreement with yourself, not out of fear of losing or hurting someone. A day for relationships and plain honesty."),
        TarotCard("major_07_chariot", "Колесница", "The Chariot",
            "Движение к цели через собранную волю. Возница правит двумя сфинксами, что тянут в разные стороны, и удерживает их не вожжами, а внутренней сосредоточенностью. Это победа через дисциплину, напор и умение свести противоречия в один вектор. Опасность — превратить драйв в упрямую гонку напролом и потерять само направление.",
            "Momentum toward a goal through gathered will. The charioteer drives two sphinxes pulling opposite ways and holds them not by reins but by inner focus. This is victory through discipline, drive and the knack of folding contradictions into a single direction. The danger is turning that drive into a stubborn charge that loses the direction itself.",
            "Соберитесь и держите курс, не давая противоречивым порывам растащить вас. Уместны решимость и трезвый самоконтроль.",
            "Gather yourself and hold the course, not letting conflicting impulses pull you apart. Resolve and level-headed self-control fit the day."),
        TarotCard("major_08_strength", "Сила", "Strength",
            "Мягкая власть над собой, что укрощает не битвой, а спокойствием. Женщина смыкает пасть льва без усилия — это про терпение, достоинство и тёплое мужество, которое сильнее давления. Проявляется там, где нужно совладать со страхом, гневом или страстью, не подавляя их, а приручая. Тень — самоедство и злость, загнанная внутрь до поры.",
            "A gentle mastery of oneself that tames not by fighting but by calm. The woman closes the lion's jaws effortlessly — this is patience, dignity and a warm courage stronger than any force. It appears where fear, anger or desire must be met and gentled rather than crushed. Its shadow is self-reproach and anger swallowed down until it festers.",
            "Действуйте терпеливо и по-доброму, особенно к себе. Раздражение сегодня не советчик — приручите его, а не гоните.",
            "Act patiently and kindly, above all toward yourself. Irritation is a poor adviser today — gentle it rather than banish it."),
        TarotCard("major_09_hermit", "Отшельник", "The Hermit",
            "Осознанное одиночество ради света внутри. Отшельник поднимается на вершину с фонарём, в котором горит собственная звезда: он ищет смысл там, где стихает шум чужих голосов. Это время замедлиться, разобраться в себе, свериться с внутренним компасом. Обратная сторона — изоляция, когда уединение становится бегством от людей и жизни.",
            "A chosen solitude for the sake of an inner light. The Hermit climbs to the peak with a lantern holding his own star; he seeks meaning where the noise of other voices fades. This is a time to slow down, sort yourself out and check your inner compass. The reverse is isolation, when retreat becomes a flight from people and from life.",
            "Выделите время побыть наедине со своими мыслями и не заполняйте тишину суетой. День для честного взгляда внутрь.",
            "Set aside time alone with your thoughts and don't fill the quiet with busyness. A day for an honest look inward."),
        TarotCard("major_10_wheel", "Колесо Фортуны", "Wheel of Fortune",
            "Поворот судьбы и вечная смена сезонов жизни. Колесо напоминает: всё движется по кругу — за спадом идёт подъём, за завершением новое начало, и ни одна фаза не длится вечно. Это удачный случай, перемена обстоятельств, узел, где сходятся закономерность и везение. Соблазн аркана — пассивно ждать милости фортуны, вместо того чтобы поймать момент.",
            "A turn of fate and the endless change of life's seasons. The Wheel reminds you that all things move in circles — a rise follows a fall, a new beginning follows an ending, and no phase lasts forever. This is a lucky break, a shift of circumstance, the knot where pattern and chance meet. Its temptation is waiting passively for fortune's favor instead of seizing the moment.",
            "Примите перемену как часть движения и не цепляйтесь за уходящее. Заметив удачную возможность, не медлите — окно недолгое.",
            "Accept the change as part of the flow and don't cling to what's leaving. When a lucky opening shows, don't dally — the window is brief."),
        TarotCard("major_11_justice", "Справедливость", "Justice",
            "Равновесие, истина и закон причины и следствия. Правосудие держит меч и весы: каждое действие возвращается ответом, и то, что посеяно, определяет урожай. Это про честность с собой, ясные договорённости и готовность отвечать за сделанное. Тень аркана — холодная бухгалтерия правоты и суд, в котором нет места живому пониманию.",
            "Balance, truth and the law of cause and effect. Justice holds a sword and scales: every act returns as an answer, and what is sown decides the harvest. This is honesty with yourself, clear agreements and a willingness to own what you've done. The arcanum's shadow is a cold accounting of who is right, a verdict with no room for living understanding.",
            "Поступайте по совести и взвешивайте решения, глядя на факты, а не на желания. День для честных договорённостей и ясности.",
            "Act by your conscience and weigh decisions on facts, not on wishes. A day for fair agreements and clarity."),
        TarotCard("major_12_hanged", "Повешенный", "The Hanged Man",
            "Пауза, в которой мир поворачивается другой стороной. Повешенный висит по своей воле, и эта добровольная остановка дарит новый угол зрения: то, что казалось тупиком, вдруг открывается иначе. Аркан о смирении, отпускании контроля и жертве малым ради большего понимания. Ловушка — застрять в подвешенности и примерить удобную роль страдальца.",
            "A pause in which the world turns to show another side. The Hanged Man hangs of his own accord, and this willing halt grants a fresh angle: what looked like a dead end suddenly reads differently. The card is about surrender, releasing control and giving up something small for a larger understanding. The trap is getting stuck in the suspension and trying on the comfortable role of martyr.",
            "Остановитесь и посмотрите на ситуацию под другим углом — не форсируйте её. Сегодня сила в принятии, а не в нажиме.",
            "Stop and look at the situation from another angle — don't force it. Today the strength is in acceptance, not in pushing.")
        ,
        TarotCard("major_13_death", "Смерть", "Death",
            "Завершение, расчищающее место обновлению. Смерть в Таро почти никогда не буквальна: это неизбежный переход, когда отжившее уходит, чтобы дать проклюнуться новому. За всадником встаёт солнце — конец здесь всегда сцеплен с рассветом. Трудность одна: страх отпустить и попытка удержать то, что уже стало прошлым.",
            "An ending that clears the ground for renewal. In tarot, Death is almost never literal: it is the inevitable passage where the outworn departs so the new can break through. Behind the rider a sun is rising — here an end is always linked to a dawn. The one difficulty is the fear of letting go and the effort to hold what has already become the past.",
            "Отпустите то, что отжило, честно и без театра. День, чтобы закрыть страницу и оставить дверь открытой новому.",
            "Release what has run its course, honestly and without drama. A day to close a chapter and leave the door open to the new."),
        TarotCard("major_14_temperance", "Умеренность", "Temperance",
            "Искусство смешивать несмешиваемое и держать середину. Ангел переливает воду меж двух чаш, не пролив ни капли, — это про алхимию терпения, где крайности соединяются в спокойное течение. Аркан говорит о балансе, исцелении, мере и умении находить третий, примиряющий путь. Его вялая сторона — бесконечное выжидание и откладывание вместо мягкого действия.",
            "The art of blending the unblendable and holding the middle. The angel pours water between two cups without spilling a drop — an alchemy of patience where extremes merge into a calm flow. The card speaks of balance, healing, moderation and the knack of finding a reconciling third way. Its sluggish side is endless waiting and delay in place of gentle action.",
            "Ищите золотую середину и не бросайтесь в крайности — смешивайте, а не выбирайте. Хорошо для примирения и восстановления сил.",
            "Seek the middle way and don't lurch to extremes — blend rather than choose. Good for reconciliation and rebuilding your strength."),
        TarotCard("major_15_devil", "Дьявол", "The Devil",
            "Привязанность, что держит крепче любых цепей. Дьявол показывает наши зависимости, соблазны и договоры с тем, что вредит, — а приглядевшись, видишь: оковы на шее свободны, и держит нас собственное согласие. Аркан о материальном плене, страсти, деньгах и власти инстинкта. Тень — привычно оправдывать то, что медленно разрушает.",
            "An attachment that binds tighter than any chain. The Devil shows our dependencies, temptations and pacts with what harms us — and, looked at closely, the collar hangs loose, and it is our own consent that holds us. The card speaks of material captivity, craving, money and the pull of instinct. Its shadow is the habit of excusing what slowly wears you down.",
            "Честно посмотрите, что вас держит и что вы сами выбираете терпеть. День осознать соблазн — и признать, где цепь расстёгнута.",
            "Look honestly at what binds you and what you choose to endure. A day to see the temptation — and to notice where the chain is already unclasped."),
        TarotCard("major_16_tower", "Башня", "The Tower",
            "Внезапный слом того, что стояло на неправде. Молния бьёт в башню, и рушится конструкция, построенная на ложном основании, — иллюзия, договор с собой, шаткая опора. Это болезненно, но освобождающе: удар сносит фальшь и открывает под ней твёрдую землю. Труднее всего — не цепляться за обломки и не отстраивать заново то, чему пора было упасть.",
            "The sudden collapse of what stood on a lie. Lightning strikes the tower and down comes a structure built on a false footing — an illusion, a bargain with yourself, a shaky support. It is painful yet freeing: the blow tears off the false front and reveals solid ground beneath. The hardest part is not clinging to the rubble and not rebuilding what was meant to fall.",
            "Не держитесь за рушащееся — за сломом откроется правда и опора понадёжнее. Будьте гибки к внезапной перемене.",
            "Don't hold on to what's collapsing — behind the break lies the truth and a sounder footing. Stay flexible with the sudden change."),
        TarotCard("major_17_star", "Звезда", "The Star",
            "Тихий свет и вера в лучшее после пережитой бури. Обнажённая фигура льёт воду на землю и в источник, ничего не тая, — это состояние надежды, обновления и мягкого исцеления, когда душа снова открывается миру. Аркан о вдохновении, спокойной ясности и ощущении, что путь верен. Его слабое место — уплыть в мечты и любоваться звездой вместо того, чтобы идти к ней.",
            "A quiet light and faith in what's ahead after the storm has passed. The nude figure pours water onto the land and back into the spring, holding nothing back — a state of hope, renewal and gentle healing as the soul opens to the world again. The card is about inspiration, calm clarity and the sense that the path is right. Its weak spot is drifting into daydreams, admiring the star instead of walking toward it.",
            "Позвольте себе надеяться и мечтать — но подкрепите мечту хотя бы одним шагом. День для восстановления и веры в свой путь.",
            "Allow yourself to hope and dream — but back the dream with at least one step. A day for recovery and faith in your path."),
        TarotCard("major_18_moon", "Луна", "The Moon",
            "Сумеречный мир, где не всё то, чем кажется. Луна освещает дорогу неверным светом: страхи растут тенями, интуиция шепчет вперемешку с тревогой, а подсознание поднимает наверх то, что днём молчит. Это про иллюзии, смутные чувства и необходимость идти сквозь неясность, доверяя чутью. Опасность — принять собственные страхи за факты и заблудиться в потёмках.",
            "A twilight world where not all is as it seems. The Moon lights the road with an uncertain glow: fears grow into shadows, intuition whispers mixed with unease, and the unconscious brings up what stays silent by day. This is about illusion, murky feelings and the need to move through the unclear while trusting your instinct. The danger is mistaking your own fears for facts and losing your way in the dark.",
            "Не принимайте важных решений на эмоциях и не верьте каждой тревоге. Доверьтесь чутью, а не панике, и дождитесь ясного света.",
            "Don't make big decisions on raw emotion, and don't believe every worry. Trust your instinct rather than panic, and wait for clearer light."),
        TarotCard("major_19_sun", "Солнце", "The Sun",
            "Полдень, ясность и простая радость быть живым. Солнце заливает светом всё, что было спрятано в тени: истина выходит наружу, дела складываются, а внутри разливается тепло и уверенность ребёнка, которому нечего скрывать. Аркан об успехе, витальности, честности и удовольствии от жизни. Единственная его тень — самоуверенность и показная бравада, когда света становится слишком много.",
            "High noon, clarity and the simple joy of being alive. The Sun floods everything once hidden in shadow: truth comes out, matters fall into place, and inside spreads the warmth and confidence of a child with nothing to hide. The card is about success, vitality, honesty and the pleasure of living. Its only shadow is overconfidence and showy bravado when the light grows too bright.",
            "Радуйтесь открыто и делитесь теплом — день благоприятен почти во всём. Хорошее время быть на виду и говорить прямо.",
            "Rejoice openly and share your warmth — the day favors almost everything. A good time to be seen and to speak plainly."),
        TarotCard("major_20_judgement", "Суд", "Judgement",
            "Пробуждение, зов и большая переоценка пройденного. Ангельская труба поднимает фигуры из саркофагов — момент, когда честно оглядываешься на прожитое, слышишь своё призвание и отвечаешь на него. Аркан о прощении, обновлении и втором шансе, о готовности начать заново с новым пониманием себя. Тень — превратить итог в суровый приговор себе и застрять в вине.",
            "An awakening, a call and a great reappraisal of the road behind you. The angel's trumpet lifts figures from their tombs — the moment you look back honestly on what you've lived, hear your calling and answer it. The card is about forgiveness, renewal and a second chance, the readiness to begin again with a new understanding of yourself. Its shadow is turning the reckoning into a harsh sentence and getting stuck in guilt.",
            "Оцените пройденное честно и без приговора, затем ответьте на внутренний зов. День прощения — себе в том числе — и нового старта.",
            "Weigh the road behind you honestly and without a sentence, then answer the inner call. A day of forgiveness — yours included — and a fresh start."),
        TarotCard("major_21_world", "Мир", "The World",
            "Завершение большого цикла и чувство целостности. Танцующая фигура в венке замкнула круг: пазл сложился, путь пройден, разрозненное соединилось в единое целое. Аркан о достижении, интеграции опыта и заслуженной полноте, о гармонии с миром и собой. Единственная сложность — страх поставить точку и шагнуть в следующий круг, ведь за завершением всегда новое начало.",
            "The close of a great cycle and a sense of wholeness. The dancing figure within the wreath has completed the round: the pieces fit, the journey is done, the scattered has joined into one. The card is about accomplishment, the integration of experience and an earned fullness, harmony with the world and yourself. The only difficulty is the fear of drawing the line and stepping into the next round, for every completion holds a new beginning.",
            "Отпразднуйте достигнутое и позвольте себе почувствовать полноту. Хорошо завершать дела, подводить итоги и благодарить.",
            "Celebrate what you've reached and let yourself feel the fullness. Good for finishing things, taking stock and giving thanks."),

        // --- Жезлы (огонь: воля, действие, энергия) ---
        TarotCard("wands_01", "Туз Жезлов", "Ace of Wands",
            "Первая искра огня — чистый импульс к жизни и творчеству. Из облака протянута рука с прорастающим жезлом: рождается вдохновение, желание действовать, зачаток нового дела или страсти. Это семя воли, в котором всё ещё впереди. Но пламя это летучее — без первого реального шага оно вспыхивает и гаснет.",
            "The first spark of fire — a pure impulse toward life and creation. A hand reaches from a cloud holding a sprouting wand: inspiration is born, the urge to act, the seed of a new venture or passion. This is the seed of will, with everything still ahead. Yet the flame is fickle — without a first real step it flares and dies.",
            "Хватайтесь за идею, пока она горит, и сделайте первый ощутимый шаг. День энтузиазма и смелого начала.",
            "Grab the idea while it burns and take a first tangible step. A day of enthusiasm and a bold beginning."),
        TarotCard("wands_02", "Двойка Жезлов", "Two of Wands",
            "Мир в ладони и вопрос, куда направить силу. Человек стоит на стене с глобусом в руке, между уютным двором и открытым горизонтом: первый успех есть, но настоящий путь только выбирается. Это про планирование, личную власть и смелость замахнуться на большее. Слабое место — застрять в раздумьях и променять решение на вечное потом.",
            "The world in your palm and the question of where to aim your power. A figure stands on a rampart holding a globe, between a familiar courtyard and an open horizon: the first success is here, but the real path is still being chosen. This is planning, personal authority and the nerve to aim higher. The weak spot is stalling in thought and trading the decision for an eternal later.",
            "Наметьте цель и дальний горизонт, затем выберите направление, а не откладывайте выбор. Хорошо строить планы и решаться на большее.",
            "Set a goal and a far horizon, then choose a direction rather than defer it. Good for making plans and daring to reach further."),
        TarotCard("wands_03", "Тройка Жезлов", "Three of Wands",
            "Первые результаты и взгляд вдаль, за которым уже плывут корабли. Фигура на возвышении смотрит на море: замысел запущен, силы вложены, пришло время расширения и ожидания отдачи. Аркан о перспективе, торговле, сотрудничестве и готовности выйти за привычные берега. Оттенок вызова — нетерпение и сомнение в пути, когда результат виден ещё не сразу.",
            "First results and a gaze into the distance where ships are already sailing. A figure on a height looks out to sea: the plan is launched, the effort is spent, and the time of expansion and waiting for the return has come. The card is about prospects, trade, cooperation and the readiness to leave familiar shores. Its challenge is impatience and doubt while the outcome is not yet in sight.",
            "Смотрите шире и не бойтесь выходить за привычные границы. День роста и перспектив — дайте начатому время дойти.",
            "Look wider and don't fear stepping past familiar limits. A day of growth and prospects — give what you've started time to arrive."),
        TarotCard("wands_04", "Четвёрка Жезлов", "Four of Wands",
            "Радостная веха и надёжная опора под ногами. Четыре жезла образуют праздничные врата, за ними — гирлянды, дом и встречающие: этап пройден, есть повод разделить радость с близкими. Аркан о стабильности, гармонии, семье и заслуженном торжестве. Тонкий вызов — позволить себе просто порадоваться, не отравляя момент тревогой о будущем.",
            "A joyful milestone and firm ground underfoot. Four wands form a festive gateway, and beyond it garlands, a home and people welcoming you: a stage is complete, a reason to share the joy with those close. The card is about stability, harmony, family and a well-earned celebration. Its subtle challenge is letting yourself simply rejoice without souring the moment with worry about the future.",
            "Порадуйтесь достигнутому в кругу близких и позвольте себе передышку. Хорошо для встреч, дома и благодарности.",
            "Celebrate what you've reached among loved ones and allow yourself a breather. Good for gatherings, home and gratitude."),
        TarotCard("wands_05", "Пятёрка Жезлов", "Five of Wands",
            "Столкновение энергий, где каждый машет своим жезлом. Пятеро сошлись в шумной потасовке — не война, а суматоха соперничества, споров и борьбы за место под солнцем. Аркан о конкуренции, разноголосице и трении, в котором, впрочем, закаляется сила. Тень — конфликт ради конфликта и распыление задора на пустые стычки.",
            "A clash of energies where everyone swings their own wand. Five figures meet in a noisy scuffle — not war but the commotion of rivalry, argument and jostling for a place in the sun. The card is about competition, a clamor of voices and friction that, for all that, tempers your strength. Its shadow is conflict for its own sake and squandering your fire on empty skirmishes.",
            "Не втягивайтесь в пустые стычки — направьте пыл в дело и слушайте чужие доводы. День разногласий, держите фокус на цели.",
            "Don't get pulled into empty skirmishes — channel the heat into work and hear out the other side. A day of friction; keep your focus on the goal."),
        TarotCard("wands_06", "Шестёрка Жезлов", "Six of Wands",
            "Заслуженный триумф и признание на виду у всех. Всадник в венке едет верхом среди приветствующей толпы: усилия замечены, победа состоялась, и это приятный, честно добытый успех. Аркан о лидерстве, хороших новостях и уверенности, что несёшь себя достойно. Оборотная сторона — привязать самооценку к аплодисментам и сникнуть, когда они смолкнут.",
            "A well-earned triumph and recognition in full view. A rider crowned with laurel moves through a cheering crowd: the effort is noticed, the victory is real, and it is a pleasant, fairly won success. The card is about leadership, good news and the confidence of carrying yourself well. The flip side is tying your worth to the applause and deflating when it fades.",
            "Примите похвалу с достоинством и идите вперёд, не завися от чужих оваций. День достижений и добрых вестей.",
            "Accept the praise with grace and move on, not hostage to others' applause. A day of achievements and good news."),
        TarotCard("wands_07", "Семёрка Жезлов", "Seven of Wands",
            "Стойка на возвышении, где приходится защищать своё. Один против шести жезлов, тянущихся снизу: у вас есть позиция, преимущество и правота, но их нужно отстоять, не отступив. Аркан о смелости, убеждениях и умении держать удар. Ловушка — уйти в глухую оборону и обороняться там, где на вас, по сути, никто не нападает.",
            "A stand on higher ground where you must defend what's yours. One figure against six wands reaching up from below: you hold the position, the advantage and the right of it, but they have to be held without retreat. The card is about courage, conviction and the ability to take a hit. The trap is sinking into blanket defensiveness, guarding against an attack that isn't really there.",
            "Держите свою линию, если уверены в правоте, но проверьте, реальна ли угроза. День требует смелости и упорства.",
            "Hold your line if you're sure you're right, but check whether the threat is real. The day calls for courage and persistence."),
        TarotCard("wands_08", "Восьмёрка Жезлов", "Eight of Wands",
            "Восемь жезлов летят по небу — стремительность, с которой события набирают ход. Ничто не стоит на месте: приходят новости, ускоряются дела, разрешается то, что застряло, и всё несётся к развязке. Аркан о скорости, сообщениях, дороге и своевременном действии. Его риск — спешка без разбора, когда торопишься так, что не успеваешь целиться.",
            "Eight wands fly across the sky — the speed with which events pick up their pace. Nothing stands still: news arrives, matters accelerate, what was stuck breaks loose, and everything rushes toward resolution. The card is about swiftness, messages, travel and well-timed action. Its risk is haste without discernment, hurrying so fast you have no time to aim.",
            "Действуйте быстро и не откладывайте — момент летит и ждать не будет. Ждите новостей и сообщений, отвечайте вовремя.",
            "Act quickly and don't delay — the moment is flying and won't wait. Expect news and messages, and answer in good time."),
        TarotCard("wands_09", "Девятка Жезлов", "Nine of Wands",
            "Последний рубеж, где стоишь на страже из последних сил. Раненый, но не сломленный воин опирается на жезл, за спиной — частокол из восьми других: почти всё пройдено, но усталость и настороженность велят ждать нового удара. Аркан о выносливости, границах и упорстве вопреки измотанности. Тень — оборонять себя из старых обид, видя врага там, где его уже нет.",
            "A last frontier where you keep watch on your final reserves. A wounded but unbroken figure leans on a staff, a palisade of eight more behind him: nearly all is behind you, yet fatigue and wariness brace for one more blow. The card is about endurance, boundaries and persistence in spite of exhaustion. Its shadow is defending yourself out of old wounds, seeing an enemy where none remains.",
            "Не сдавайтесь у самой цели, но берегите остаток сил и не ждите удара отовсюду. День упорства — второе дыхание уже рядом.",
            "Don't give up right at the goal, but spare what strength is left and don't brace for a blow from everywhere. A day of persistence — a second wind is near."),
        TarotCard("wands_10", "Десятка Жезлов", "Ten of Wands",
            "Ноша из десяти жезлов, взваленная на одни плечи. Согнувшаяся фигура тащит охапку к дому: дело почти доведено, но взято на себя слишком много, и груз ответственности давит сильнее самой задачи. Аркан о перегрузе, долге и привычке нести всё в одиночку. Точка роста — признать, что часть тяжести можно отпустить или разделить.",
            "A load of ten wands heaved onto a single pair of shoulders. A bent figure hauls the bundle toward home: the work is nearly done, but too much has been taken on, and the weight of responsibility presses harder than the task itself. The card is about overload, duty and the habit of carrying everything alone. The point of growth is admitting that some of the weight can be set down or shared.",
            "Разгрузите себя и делегируйте лишнее — не всё обязано лежать на вас. День о границах нагрузки и умении просить помощь.",
            "Lighten your load and delegate the excess — not everything has to rest on you. A day about the limits of what you carry and the skill of asking for help."),
        TarotCard("wands_11", "Паж Жезлов", "Page of Wands",
            "Юный вестник огня, в котором всё горит любопытством. Паж стоит с жезлом, разглядывая его как обещание приключения: приходит новость о начинании, вспыхивает интерес, зовёт неизведанное. Это свежий энтузиазм, готовность пробовать и творить без оглядки. Незрелая сторона стихии — разбросанность и множество дел, брошенных на первой же искре.",
            "A young herald of fire in whom everything blazes with curiosity. The Page stands with a wand, studying it like a promise of adventure: word of a new venture arrives, interest flares, the unknown calls. This is fresh enthusiasm, a readiness to try and create without a backward glance. The element's unripe side is scattering, a heap of things dropped at the very first spark.",
            "Пробуйте, экспериментируйте и загоритесь идеей, но выберите одну, чтобы довести до конца. День открытости и лёгкого авантюризма.",
            "Try, experiment and catch fire from an idea, but pick one to see through. A day of openness and light adventure."),
        TarotCard("wands_12", "Рыцарь Жезлов", "Knight of Wands",
            "Пламя в движении — страсть, порыв и стремительный бросок вперёд. Рыцарь на вздыбленном коне рвётся в путь, не терпя промедления: он воплощает азарт, отвагу и заразительную энергию действия. Хорош там, где нужен смелый рывок и живой напор. Незрелость стихии — импульсивность, вспышка без выдержки и дела, брошенные на полпути.",
            "Fire in motion — passion, impulse and a headlong charge forward. The Knight on a rearing horse strains to be off, brooking no delay: he embodies drive, daring and the contagious energy of action. He is good where a bold dash and living momentum are needed. The element's immaturity is impulsiveness, a flare with no staying power and things abandoned halfway.",
            "Действуйте смело и первыми, но не растрачивайте пыл на всё подряд. День инициативы и движения — доводите начатое.",
            "Act boldly and be the first to move, but don't scatter your fire on everything at once. A day of initiative and movement — finish what you start."),
        TarotCard("wands_13", "Королева Жезлов", "Queen of Wands",
            "Тёплая, уверенная сила, что зажигает других одним присутствием. Королева на троне со львами и подсолнухом держит жезл и чёрную кошку: в ней харизма, независимость и живое обаяние, притягивающее людей. Это зрелость огня — умение вдохновлять, вести и быть собой ярко и щедро. Её тень — ревность и потребность быть в центре любой сцены.",
            "A warm, self-assured strength that lights others up by mere presence. The Queen on a throne of lions and sunflowers holds a wand and a black cat: in her live charisma, independence and a vivid charm that draws people in. This is the maturity of fire — the gift of inspiring, leading and being yourself brightly and generously. Her shadow is jealousy and a need to be the center of every scene.",
            "Будьте собой ярко и щедро, зажигайте других своим теплом. День личного магнетизма и творчества.",
            "Be yourself brightly and generously, and light others with your warmth. A day of personal magnetism and creativity."),
        TarotCard("wands_14", "Король Жезлов", "King of Wands",
            "Зрелая воля, видящая цель за горизонтом и ведущая к ней. Король с жезлом и саламандрами на троне — прирождённый вдохновитель и стратег: он мыслит масштабно, зажигает идеей и берёт ответственность за большой замысел. Это владение огнём, ставшее лидерством и предпринимательским чутьём. Тень аркана — деспотизм и нетерпимость к тем, кто движется в другом темпе.",
            "A mature will that sees the goal beyond the horizon and leads toward it. The King with his wand and salamander throne is a born motivator and strategist: he thinks large, fires people with a vision and takes responsibility for the big idea. This is fire grown into leadership and entrepreneurial instinct. The arcanum's shadow is tyranny and impatience with those who move at another pace.",
            "Берите инициативу и мыслите масштабно, но оставьте другим право на свой темп. День для смелых решений и лидерства.",
            "Take the initiative and think big, while leaving others the right to their own pace. A day for bold decisions and leadership."),

        // --- Кубки (вода: чувства, отношения, интуиция) ---
        TarotCard("cups_01", "Туз Кубков", "Ace of Cups",
            "Переполненная чаша, из которой льётся любовь. Рука из облака держит кубок с пятью струями, голубь опускает облатку — это начало чувства, открытое сердце, источник нежности и духовной близости. Семя эмоциональной жизни, готовое расцвести в отношения, творчество или сострадание. Единственная преграда — страх впустить и снова стать уязвимым.",
            "An overflowing chalice from which love pours out. A hand from a cloud holds a cup with five streams, a dove lowering a wafer — this is the start of feeling, an open heart, a wellspring of tenderness and spiritual closeness. The seed of emotional life, ready to flower into a bond, creativity or compassion. The one barrier is the fear of letting it in and becoming vulnerable again.",
            "Откройтесь чувствам и доброте — своим и чужим — не защищаясь заранее. День нежности, принятия и тёплых связей.",
            "Open to feeling and kindness — yours and others' — without armoring up in advance. A day of tenderness, acceptance and warm bonds."),
        TarotCard("cups_02", "Двойка Кубков", "Two of Cups",
            "Встреча двоих на равных и рождение взаимности. Двое обмениваются кубками под крылатым львом: возникает притяжение, союз, взаимное признание и уважение — партнёрство, где каждый остаётся собой. Аркан о любви, дружбе, примирении и договоре сердец. Уязвимость — идеализировать другого и раствориться в союзе, потеряв собственные опоры.",
            "A meeting of two as equals and the birth of mutuality. A pair exchange cups beneath a winged lion: attraction arises, a union, a mutual recognition and respect — a partnership where each stays themselves. The card is about love, friendship, reconciliation and a pact of hearts. Its vulnerability is idealizing the other and dissolving into the bond, losing your own footing.",
            "Цените взаимность и стройте мосты, оставаясь при этом собой. Хорошо для отношений, партнёрства и примирения.",
            "Value mutuality and build bridges while staying yourself. Good for relationships, partnership and reconciliation."),
        TarotCard("cups_03", "Тройка Кубков", "Three of Cups",
            "Три поднятых кубка — тепло круга, где радость общая. Подруги танцуют среди плодов урожая: это дружба, поддержка, праздник и чувство принадлежности к своим. Аркан о душевной близости, взаимной радости и умении делить хорошее. Тень — прятаться в веселье от того, что давно пора решить в одиночку.",
            "Three cups raised high — the warmth of a circle where joy is shared. Companions dance among the fruits of harvest: this is friendship, support, celebration and the sense of belonging to your own. The card is about closeness, mutual gladness and the knack of sharing the good. Its shadow is hiding in the festivity from something you have long needed to face alone.",
            "Проведите время с теми, кто дорог, и не стесняйтесь опереться на них. День встреч, поддержки и совместной радости.",
            "Spend time with those dear to you and don't be shy to lean on them. A day of gatherings, support and shared joy."),
        TarotCard("cups_04", "Четвёрка Кубков", "Four of Cups",
            "Скучающий взгляд, что не замечает протянутой чаши. Фигура под деревом отвернулась от трёх кубков, а четвёртый ей предлагает рука из облака: пресыщение, апатия и хандра застят то доброе, что рядом. Аркан о внутренней паузе, недовольстве и упущенных возможностях. Точка роста — стряхнуть равнодушие и увидеть ценность в уже имеющемся.",
            "A bored gaze that overlooks the cup held out to it. A figure under a tree has turned from three cups while a fourth is offered by a hand from a cloud: satiety, apathy and gloom veil the good that is right there. The card is about an inward pause, discontent and missed chances. The point of growth is shaking off the indifference and seeing the worth in what you already have.",
            "Оглянитесь — рядом есть то, чего вы не замечаете за хандрой. Стряхните скуку и откройтесь предложенному.",
            "Look around — something near you goes unnoticed behind the gloom. Shake off the boredom and open to what's offered."),
        TarotCard("cups_05", "Пятёрка Кубков", "Five of Cups",
            "Печаль над пролитым, за которой не видно уцелевшего. Фигура в плаще склонилась над тремя опрокинутыми кубками, но за спиной стоят ещё два полных, а вдали — мост к дому. Аркан о потере, сожалении и горе, которое реально, но не окончательно. Тень — смотреть только на разбитое, забыв, что часть опор осталась целой.",
            "Grief over what's spilled, blind to what still stands. A cloaked figure bows over three toppled cups, but two full ones remain behind, and a bridge home lies in the distance. The card is about loss, regret and a sorrow that is real yet not final. Its shadow is looking only at what's broken, forgetting that some supports are still whole.",
            "Погрустите, а затем обернитесь: часть опор ещё цела и ждёт вас. День принять утрату и увидеть оставшееся.",
            "Grieve, then turn around: some supports still stand and wait for you. A day to accept the loss and see what remains."),
        TarotCard("cups_06", "Шестёрка Кубков", "Six of Cups",
            "Тёплый свет прошлого и невинная доброта. Ребёнок протягивает другому кубок с цветами в уютном дворе: всплывают дорогие воспоминания, ностальгия, простая щедрость и нежность к своим корням. Аркан о доме детства, старых связях и бескорыстной заботе. Оттенок вызова — уйти жить во вчера и черпать силы только из прошлого, не замечая настоящего.",
            "The warm light of the past and an innocent kindness. A child hands another a cup of flowers in a snug courtyard: dear memories surface, nostalgia, a simple generosity and tenderness toward your roots. The card is about the home of childhood, old ties and selfless care. Its challenge is moving in to live in yesterday, drawing strength only from the past while missing the present.",
            "Вспомните доброе и подарите заботу без счёта, но живите днём сегодняшним. Хорошо для семьи, детей и старых связей.",
            "Recall the good and give care freely, yet live in today. Good for family, children and old bonds."),
        TarotCard("cups_07", "Семёрка Кубков", "Seven of Cups",
            "Семь кубков в облаках, полных заманчивых видений. Фигура замерла перед миражами: богатство, любовь, слава, тайна — так много желанного, но не всё реально, и часть чаш таит пустоту. Аркан о мечтах, фантазиях и обилии соблазнов, в котором легко потеряться. Ловушка — паралич от выбора и грёзы вместо конкретного шага.",
            "Seven cups in the clouds, brimming with alluring visions. A figure freezes before the mirages: riches, love, glory, mystery — so much to want, yet not all of it real, and some cups hold only emptiness. The card is about dreams, fantasies and a wealth of temptations easy to get lost in. The trap is choice paralysis and reverie in place of a concrete step.",
            "Отделите настоящее желание от фантазии и выберите одно, а не любуйтесь всеми сразу. День не распыляться на миражи.",
            "Separate real desire from fantasy and pick one instead of admiring them all. A day not to scatter yourself on mirages."),
        TarotCard("cups_08", "Восьмёрка Кубков", "Eight of Cups",
            "Тихий уход в поисках того, что по-настоящему наполняет. Фигура под убывающей луной оставляет восемь ровно составленных кубков и идёт в горы: внешне всё сложено, но чего-то главного не хватает, и душа зовёт дальше. Аркан о зрелом расставании, поиске смысла и честности с собой. Тень — бегать по кругу, меняя декорации, вместо того чтобы разобраться в сути.",
            "A quiet departure in search of what truly fills you. Beneath a waning moon a figure leaves eight neatly stacked cups and walks into the mountains: outwardly all is in order, yet something essential is missing, and the soul calls onward. The card is about a mature parting, a search for meaning and honesty with yourself. Its shadow is running in circles, swapping the scenery instead of facing the heart of the matter.",
            "Оставьте то, что исчерпано, и идите за глубиной, не оглядываясь с виной. День честного признания: мне нужно другое.",
            "Leave what's exhausted and go toward depth without a guilty backward glance. A day for an honest admission: I need something else."),
        TarotCard("cups_09", "Девятка Кубков", "Nine of Cups",
            "Довольство сытого сердца и исполненное желание. Фигура сидит, скрестив руки, перед аркой из девяти кубков — карту недаром зовут «желание»: то, о чём мечталось, сбывается, и приходит уют, радость и чувство достатка. Аркан об удовольствии, благополучии и заслуженном наслаждении жизнью. Тень — самодовольство и остановка, когда сытость гасит стремление расти.",
            "The contentment of a satisfied heart and a wish come true. A figure sits with folded arms before an arc of nine cups — the card is aptly nicknamed the wish: what was longed for arrives, bringing comfort, gladness and a sense of plenty. The card is about pleasure, well-being and an earned enjoyment of life. Its shadow is smugness and a standstill, when fullness quenches the drive to grow.",
            "Позвольте себе удовольствие и благодарность за то, чего достигли. Хороший день радоваться тому, что есть, не переставая мечтать дальше.",
            "Allow yourself pleasure and gratitude for what you've reached. A good day to enjoy what you have while still dreaming further."),
        TarotCard("cups_10", "Десятка Кубков", "Ten of Cups",
            "Радуга из десяти кубков над домом, где царит лад. Семья с поднятыми руками, дети в танце — это эмоциональная полнота, гармония в отношениях и счастье, разделённое с близкими. Аркан о душевном доме, принадлежности и мире в сердце. Тонкий вызов — не отравлять идиллию страхом, что она слишком хороша и потому хрупка.",
            "A rainbow of ten cups above a home where harmony reigns. A family with arms raised, children dancing — this is emotional fullness, harmony in relationships and happiness shared with those you love. The card is about the home of the heart, belonging and inner peace. Its subtle challenge is not to poison the idyll with a fear that it's too good and therefore fragile.",
            "Цените близость и общий лад, доверяя своему счастью, а не подозревая его. День тепла, дома и благодарности за отношения.",
            "Value closeness and harmony, trusting your happiness rather than suspecting it. A day of warmth, home and gratitude for your relationships."),
        TarotCard("cups_11", "Паж Кубков", "Page of Cups",
            "Юный вестник чувств, в чьём кубке неожиданно всплывает рыбка. Паж у моря удивлённо смотрит на неё — символ интуитивной подсказки, творческого порыва и доброй вести сердца. Это наивная искренность, нежность и готовность мечтать и чувствовать открыто. Незрелая сторона воды — обидчивость и уход в фантазии, когда мир слишком груб.",
            "A young herald of feeling, a little fish surfacing unexpectedly in his cup. The Page by the sea looks at it in wonder — a symbol of an intuitive hint, a creative impulse and good news of the heart. This is naive sincerity, tenderness and a readiness to dream and feel openly. The element's unripe side is touchiness and retreat into fantasy when the world feels too rough.",
            "Прислушайтесь к сердцу и не стыдитесь мягкости — из неё рождается вдохновение. День тёплых сообщений и творческих идей.",
            "Listen to your heart and don't be ashamed of gentleness — inspiration is born from it. A day of warm messages and creative ideas."),
        TarotCard("cups_12", "Рыцарь Кубков", "Knight of Cups",
            "Всадник, ведомый идеалом и красотой. Рыцарь неспешно едет с поднятым кубком, как посланник любви: он несёт романтическое предложение, творческий порыв, приглашение к чувству. Это движение сердцем, обаяние и стремление к возвышенному. Уязвимость стихии в нём — обещания, которые легко дать под настроение и трудно сдержать.",
            "A rider led by an ideal and by beauty. The Knight moves at an unhurried pace, cup raised like a messenger of love: he brings a romantic offer, a creative impulse, an invitation to feeling. This is moving by the heart, charm and a reach for the sublime. The element's vulnerability in him is promises easily made on a mood and hard to keep.",
            "Следуйте за красотой и добрым порывом, но обещайте лишь то, что готовы исполнить. День для романтики, искусства и примирения.",
            "Follow beauty and a kind impulse, but promise only what you're ready to keep. A day for romance, art and reconciliation."),
        TarotCard("cups_13", "Королева Кубков", "Queen of Cups",
            "Глубокая чуткость, что видит чувства прежде слов. Королева на троне у воды держит закрытый кубок, глядя в него как в глубину души: в ней сострадание, интуиция и эмоциональная мудрость, дающая опору другим. Это зрелость воды — умение чувствовать тонко и поддерживать, не теряя себя. Тень — раствориться в чужих переживаниях и забыть о собственных границах.",
            "A deep sensitivity that sees feelings before words. The Queen on her throne by the water holds a closed cup, gazing into it as into the depth of the soul: in her live compassion, intuition and an emotional wisdom that steadies others. This is the maturity of water — the gift of feeling finely and supporting without losing yourself. Her shadow is dissolving into others' emotions and forgetting your own boundaries.",
            "Будьте внимательны к чувствам — своим и чужим — но не растворяйтесь в чужой боли. День заботы, эмпатии и доверия интуиции.",
            "Be attentive to feelings — yours and others' — but don't dissolve into another's pain. A day of care, empathy and trusting your intuition."),
        TarotCard("cups_14", "Король Кубков", "King of Cups",
            "Спокойное владение чувствами среди бушующего моря. Король на троне посреди волн держит кубок и скипетр, оставаясь невозмутимым: это зрелость сердца, дипломатия и тёплая, но устойчивая сила, что не тонет в эмоциях. Аркан о душевном равновесии, сострадании и умении держать себя в руках. Тень — подавлять чувства под маской покоя, пока внутри копится буря.",
            "A calm mastery of feeling amid a raging sea. The King on his throne among the waves holds a cup and a scepter, remaining unshaken: this is maturity of the heart, diplomacy and a warm yet steady strength that does not drown in emotion. The card is about inner balance, compassion and self-possession. Its shadow is suppressing feeling behind a mask of calm while a storm gathers within.",
            "Сохраняйте душевное равновесие и поддержите других, но не прячьте собственные чувства слишком глубоко. День дипломатии и внутреннего покоя.",
            "Keep your inner balance and support others, yet don't bury your own feelings too deep. A day of diplomacy and inner peace."),

        // --- Мечи (воздух: ум, слова, решения) ---
        TarotCard("swords_01", "Туз Мечей", "Ace of Swords",
            "Меч, поднятый в короне, — прорыв ясности и торжество истины. Рука из облака держит клинок, рассекающий туман сомнений: рождается решающая мысль, честное слово, точное понимание сути. Семя разума в его лучшем виде — прямота, справедливость, интеллектуальный прорыв. Острота его двусторонняя: правда, сказанная как оружие, ранит не хуже лжи.",
            "A sword raised in a crown — a breakthrough of clarity and the triumph of truth. A hand from a cloud holds the blade cutting through the fog of doubt: a decisive thought is born, an honest word, a precise grasp of the essence. This is the seed of the mind at its best — directness, fairness, an intellectual breakthrough. Its edge cuts both ways: truth wielded as a weapon wounds no less than a lie.",
            "Назовите вещи своими именами и примите ясное решение, но выбирайте слова так, чтобы они лечили, а не резали. День истины и точных формулировок.",
            "Call things by their names and make a clear decision, but choose words that heal rather than cut. A day of truth and precise wording."),
        TarotCard("swords_02", "Двойка Мечей", "Two of Swords",
            "Хрупкое равновесие с завязанными глазами и скрещёнными мечами. Фигура сидит спиной к морю, отгородившись от чувств и не давая себе увидеть выбор: решение отложено, ум держит паузу на грани. Аркан о нерешительности, перемирии с самим собой и уходе от того, что придётся признать. Тень — избегание, которое лишь копит напряжение под повязкой.",
            "A fragile balance, blindfolded, with swords crossed. A figure sits with her back to the sea, walled off from feeling and refusing to see the choice: the decision is postponed, the mind holding a pause on a knife's edge. The card is about indecision, a truce with yourself and dodging what must be faced. Its shadow is avoidance that only stores up tension behind the blindfold.",
            "Снимите повязку и посмотрите на факты — решение всё равно придётся принять. День перестать избегать и честно взвесить обе чаши.",
            "Take off the blindfold and look at the facts — the choice must be made anyway. A day to stop avoiding and weigh both sides honestly."),
        TarotCard("swords_03", "Тройка Мечей", "Three of Swords",
            "Три меча в сердце под дождливым небом — образ боли, которую не спрятать. Аркан говорит о разочаровании, горькой правде, разрыве или ранящем слове: сердце задето, и это нужно прожить, а не отрицать. Дождь здесь очищает — за болью приходит освобождение. Тень — поселиться в обиде и снова и снова растравлять свежую рану.",
            "Three swords through a heart under a rainy sky — an image of pain there's no hiding. The card speaks of disappointment, a bitter truth, a break or a wounding word: the heart is struck, and this must be lived through rather than denied. The rain here cleanses — release follows the pain. Its shadow is settling into the hurt and reopening the fresh wound again and again.",
            "Позвольте себе прожить боль, не растравляя её и не отрицая. День принять случившееся и начать исцеление.",
            "Let yourself feel the pain without picking at it or denying it. A day to accept what happened and begin healing."),
        TarotCard("swords_04", "Четвёрка Мечей", "Four of Swords",
            "Рыцарь, застывший в покое, как на отдыхе после битвы. Три меча висят над ним, один лежит рядом — время не сражения, а тишины: уму нужна передышка, чтобы восстановиться и собраться. Аркан о паузе, отдыхе, выздоровлении и осознанном отступлении. Оттенок вызова — не перепутать полезный покой с застоем, когда пауза затягивается и превращается в бегство.",
            "A knight lying in repose, as if resting after battle. Three swords hang above him, one lies alongside — a time not for fighting but for stillness: the mind needs a respite to recover and regroup. The card is about a pause, rest, recuperation and a deliberate retreat. Its challenge is not to mistake useful quiet for stagnation when the pause drags on and turns into flight.",
            "Дайте себе передышку и не пытайтесь решить всё сразу — восстановление тоже работа. День покоя, сна и накопления сил.",
            "Give yourself a breather and don't try to solve everything at once — recovery is work too. A day of rest, sleep and gathering strength."),
        TarotCard("swords_05", "Пятёрка Мечей", "Five of Swords",
            "Победа, оставляющая горький привкус. Фигура собирает мечи с самодовольной усмешкой, пока двое побеждённых уходят прочь: выиграть удалось, но какой ценой — за спором осталась пустота и порванные связи. Аркан о конфликте, уязвлённой гордости и цене правоты любой ценой. Тень — ставить победу в споре выше отношений и не считать потерь.",
            "A victory that leaves a bitter aftertaste. A figure gathers the swords with a smug grin while two defeated ones walk away: the win came, but at what cost — behind the quarrel lies emptiness and torn ties. The card is about conflict, wounded pride and the price of being right at any cost. Its shadow is placing a win in an argument above the relationship and not counting the losses.",
            "Не доказывайте правоту любой ценой — иные победы обходятся дороже, чем стоят. День выбрать мир там, где спор бессмыслен.",
            "Don't prove your point at any cost — some wins cost more than they're worth. A day to choose peace where the argument is pointless."),
        TarotCard("swords_06", "Шестёрка Мечей", "Six of Swords",
            "Тихая переправа от бури к спокойной воде. Лодочник везёт двоих через реку, мечи стоят на борту, как груз, что берут с собой: это переход, отдаление от трудного и медленное движение к лучшему. Аркан о выздоровлении, дороге и постепенном улучшении. Оттенок вызова — не увезти с собой старые тревоги на новый берег.",
            "A quiet crossing from the storm to calmer water. A ferryman carries two passengers over the river, the swords standing upright like cargo taken along: this is a transition, a drawing away from the hard toward the better, a slow move to steadier ground. The card is about recovery, travel and gradual improvement. Its challenge is not to carry old worries with you to the new shore.",
            "Двигайтесь к более спокойным водам, оставляя тревоги на прежнем берегу. День перемен к лучшему — не тащите старое с собой.",
            "Move toward calmer waters, leaving your worries on the old shore. A day of change for the better — don't drag the old along."),
        TarotCard("swords_07", "Семёрка Мечей", "Seven of Swords",
            "Тихий уход с добычей и игра не в открытую. Фигура крадётся из лагеря с пятью мечами, оставив два позади: это хитрость, уловка, стратегия обхода — иногда чужая, иногда собственная. Аркан о лукавстве, ловкости и действии в тени. Тень — самообман и мелкая нечестность, за которую в итоге платишь доверием.",
            "A quiet getaway with the spoils and a game played out of sight. A figure sneaks from the camp with five swords, leaving two behind: this is cunning, a ploy, a strategy of going around the front — sometimes another's, sometimes your own. The card is about slyness, dexterity and acting in the shadows. Its shadow is self-deception and petty dishonesty that you ultimately pay for in trust.",
            "Действуйте честно и проверьте, где с вами лукавят или где вы лукавите сами. День осторожности и ясной стратегии.",
            "Act honestly and check where you're being played, or where you're playing yourself. A day of caution and a clear strategy."),
        TarotCard("swords_08", "Восьмёрка Мечей", "Eight of Swords",
            "Мнимая ловушка, где путы держатся на одном лишь страхе. Связанная фигура с повязкой на глазах стоит среди восьми мечей, но они не смыкают круг, и путь свободен — просто его не видно. Аркан об ощущении безвыходности, скованности мыслью и самоограничении. Тень — согласиться на роль пленника и не сделать шага, который никто, кроме страха, не запрещает.",
            "A false trap where the bonds hold by fear alone. A bound, blindfolded figure stands among eight swords, but they do not close the circle, and the way is open — it simply can't be seen. The card is about a sense of no way out, being bound by thought and self-imposed limits. Its shadow is agreeing to the role of prisoner and not taking the step that nothing but fear forbids.",
            "Оглядитесь: выход есть, его прячет страх, а не обстоятельства. День снять с себя надуманные ограничения и сделать первый шаг.",
            "Look around: there's a way out — fear hides it, not the circumstances. A day to shed imagined limits and take the first step."),
        TarotCard("swords_09", "Девятка Мечей", "Nine of Swords",
            "Бессонная ночь, когда ум множит беды в темноте. Фигура сидит на постели, схватившись за голову, а над ней висят девять мечей — это тревога, чувство вины и ночные страхи, что всегда преувеличивают. Аркан о муках разума, который сам себя терзает, хотя беда чаще в мыслях, чем в реальности. Тень — принимать тревогу за факт и верить ей больше, чем дневному свету.",
            "A sleepless night when the mind multiplies troubles in the dark. A figure sits up in bed, head in hands, nine swords hanging above — this is anxiety, guilt and the night fears that always exaggerate. The card is about the torment of a mind that wounds itself, though the trouble lives more in thought than in reality. Its shadow is taking worry for fact and trusting it over the light of day.",
            "Не верьте тревоге как факту — при свете дня она почти всегда мельче. День бережности к себе: выспитесь и говорите со страхом вслух.",
            "Don't take worry as fact — by daylight it nearly always shrinks. A day of gentleness toward yourself: rest, and speak your fear out loud."),
        TarotCard("swords_10", "Десятка Мечей", "Ten of Swords",
            "Дно, которое одновременно и конец, и обещание рассвета. Фигура лежит, пронзённая десятью мечами, но на горизонте уже светлеет небо: тяжёлое завершилось, хуже не будет, и мучительное подошло к финалу. Аркан о крахе, который расчищает почву, и об окончательной точке. Тень — драматизировать падение и застрять в роли жертвы, когда пора вставать.",
            "Rock bottom that is at once an ending and a promise of dawn. A figure lies pierced by ten swords, yet the sky is already lightening on the horizon: the hard thing is over, it won't get worse, and the agonizing has come to its close. The card is about a collapse that clears the ground and about a final full stop. Its shadow is dramatizing the fall and getting stuck in the victim's role when it's time to rise.",
            "Признайте окончание и не оживляйте отжившее — рассвет уже рядом. День отпустить и начать заново с чистого листа.",
            "Acknowledge the ending and don't revive the dead — dawn is already near. A day to let go and begin again with a clean slate."),
        TarotCard("swords_11", "Паж Мечей", "Page of Swords",
            "Юный ум, острый и настороженный, жаждущий во всём разобраться. Паж стоит на ветру с поднятым мечом, готовый учиться, наблюдать и задавать вопросы: это любознательность, бдительность и живая ясность мысли. Стихия воздуха в нём свежа и любопытна. Незрелая её сторона — колкость на язык, суждение свысока и слова, брошенные раньше, чем взвешены.",
            "A young mind, sharp and watchful, hungry to figure things out. The Page stands in the wind, sword raised, ready to learn, observe and ask questions: this is curiosity, alertness and a lively clarity of thought. The element of air in him is fresh and inquisitive. Its unripe side is a sharp tongue, judging from above and words thrown out before they're weighed.",
            "Задавайте вопросы и проверяйте факты, прежде чем делать выводы. День учиться, наблюдать и говорить точно, но без колкости.",
            "Ask questions and check the facts before drawing conclusions. A day to learn, observe and speak precisely, but without a barb."),
        TarotCard("swords_12", "Рыцарь Мечей", "Knight of Swords",
            "Мысль, рвущаяся в бой, стремительная и прямая. Рыцарь мчится сквозь бурю с занесённым мечом, не терпя ни промедления, ни возражений: это напор, решимость и скорость ума, что летит к цели. Хорош там, где нужно смело прорубить дорогу и сказать правду в лицо. Незрелость стихии — рубить сплеча, ранить словом и нестись вперёд, не думая о последствиях.",
            "A thought charging into battle, swift and straight. The Knight races through a storm with his sword raised, brooking neither delay nor objection: this is drive, resolve and a speed of mind that flies toward its aim. He is good where a road must be cut boldly and the truth spoken to someone's face. The element's immaturity is striking rashly, wounding with words and rushing ahead without a thought for the fallout.",
            "Действуйте решительно, но не рубите сплеча — сначала прицельтесь, потом бейте. День смелых слов: следите за тактом.",
            "Act decisively, but don't strike blindly — aim first, then move. A day of bold words: mind your tact."),
        TarotCard("swords_13", "Королева Мечей", "Queen of Swords",
            "Трезвый ум, видящий сквозь иллюзии. Королева на троне держит меч прямо, а другую руку протягивает — она соединяет ясность, честность и независимость с выстраданной мудростью. Это зрелость воздуха: способность мыслить чётко, ставить границы и говорить правду без жестокости. Тень — уйти в холодность и отстранённость, когда разум забывает про сердце.",
            "A clear mind that sees through illusions. The Queen on her throne holds the sword upright while extending her other hand — she joins clarity, honesty and independence with a hard-won wisdom. This is the maturity of air: the ability to think sharply, set boundaries and tell the truth without cruelty. Her shadow is retreating into coldness and detachment, when the mind forgets the heart.",
            "Мыслите чётко и говорите правду по-доброму — ясность не обязана быть резкой. День здравого смысла и честных границ.",
            "Think clearly and tell the truth kindly — clarity need not be harsh. A day of common sense and honest boundaries."),
        TarotCard("swords_14", "Король Мечей", "King of Swords",
            "Власть разума, принципа и справедливого суждения. Король на троне держит вертикальный меч — воплощение интеллекта, беспристрастности и ясной логики, что выносит честный вердикт. Это зрелость мысли: способность решать по фактам, держать слово и защищать истину. Тень — сухая логика без сердца, когда правила важнее живых людей.",
            "The authority of reason, principle and fair judgment. The King on his throne holds the sword upright — the embodiment of intellect, impartiality and clear logic that hands down an honest verdict. This is the maturity of thought: the ability to decide on facts, keep your word and defend the truth. Its shadow is dry logic without heart, when rules matter more than living people.",
            "Решайте на основе фактов и логики, беспристрастно, но не забывайте о человеке за правилами. День для анализа и честных вердиктов.",
            "Decide on facts and logic, impartially, but don't forget the person behind the rule. A day for analysis and fair verdicts."),

        // --- Пентакли (земля: дело, деньги, тело) ---
        TarotCard("pents_01", "Туз Пентаклей", "Ace of Pentacles",
            "Ладонь, протянувшая монету, — прочное семя достатка. Из облака является пентакль над цветущим садом: приходит новая возможность, ресурс, здоровое начало дела, вложения или заботы о теле. Это самое приземлённое и надёжное из начал — то, что можно взрастить в реальный результат. Тень — так жаждать гарантий, что упускаешь момент сделать первый вклад.",
            "A palm holding out a coin — a solid seed of prosperity. From a cloud a pentacle appears above a flowering garden: a new opportunity arrives, a resource, a healthy start to a venture, an investment or care for the body. This is the most grounded and dependable of beginnings — something you can grow into a real result. Its shadow is craving guarantees so badly that you miss the moment to make the first contribution.",
            "Заложите основу дела или полезной привычки — вложенное окупится сторицей. День практичного, приземлённого старта.",
            "Lay the foundation of a venture or a good habit — what you invest will pay back. A day for a practical, grounded start."),
        TarotCard("pents_02", "Двойка Пентаклей", "Two of Pentacles",
            "Жонглёр, что удерживает два пентакля в танцующей бесконечности. За спиной вздымаются волны, а он ловко балансирует между делами, деньгами и заботами: это гибкость, приоритеты и умение справляться с несколькими задачами сразу. Аркан о ритме, адаптации и подвижном равновесии. Тень — суета, в которой теряешь главное, пытаясь удержать всё одновременно.",
            "A juggler keeping two pentacles in a dancing figure-eight. Waves heave behind him as he deftly balances between tasks, money and cares: this is flexibility, priorities and the knack of handling several things at once. The card is about rhythm, adaptation and a moving equilibrium. Its shadow is a busyness in which you lose the essential while trying to hold everything at the same time.",
            "Распределите силы и не хватайтесь за всё разом — выберите, что несёте первым. День гибкости и трезвых приоритетов.",
            "Spread your energy and don't grab everything at once — choose what you carry first. A day of flexibility and sober priorities."),
        TarotCard("pents_03", "Тройка Пентаклей", "Three of Pentacles",
            "Мастер за работой, к которому прислушиваются заказчики. В соборе ремесленник обсуждает дело с двумя советчиками: замысел воплощается совместным трудом, где ценятся навык, признание и точная роль каждого. Аркан о мастерстве, сотрудничестве и первых зримых плодах. Оттенок вызова — не тянуть одеяло на себя и уметь слышать тех, кто рядом.",
            "A craftsman at work whom the patrons stop to consult. In a cathedral an artisan talks over the job with two advisers: the plan takes shape through shared effort, where skill, recognition and each person's exact role are valued. The card is about craftsmanship, collaboration and the first visible fruits. Its challenge is not to pull the credit your own way and to truly hear those beside you.",
            "Работайте в связке и учитесь у умелых — совместный труд надёжнее одиночного. День командной работы и роста навыка.",
            "Work in tandem and learn from the skilled — shared effort outlasts going it alone. A day of teamwork and growing your craft."),
        TarotCard("pents_04", "Четвёрка Пентаклей", "Four of Pentacles",
            "Крепко сжатое богатство и страх выпустить его из рук. Фигура прижимает пентакль к груди, ещё два под ногами, один на голове: это бережливость, контроль и потребность в безопасности, которая легко переходит в скупость. Аркан о накоплении, границах и удержании ресурса. Тень — так вцепиться в имеющееся, что оно перестаёт течь и работать.",
            "Wealth clutched tight and the fear of letting it slip. A figure presses a pentacle to the chest, two more beneath the feet, one on the head: this is thrift, control and a need for security that easily curdles into stinginess. The card is about saving, boundaries and holding on to a resource. Its shadow is gripping what you have so hard that it stops flowing and working.",
            "Берегите ресурсы, но не превращайте бережливость в зажим — деньги и силы должны двигаться. День о разумной мере в контроле.",
            "Guard your resources, but don't let thrift become a clench — money and energy need to move. A day about a sensible measure of control."),
        TarotCard("pents_05", "Пятёрка Пентаклей", "Five of Pentacles",
            "Двое бредут по снегу мимо освещённого окна. Витраж рядом полон света, но они его не видят: это нужда, трудный период, болезнь или чувство отверженности — а помощь при этом ближе, чем кажется. Аркан о лишениях телесных и душевных и о том, что опора рядом. Тень — гордость, которая мешает поднять голову и попросить.",
            "Two figures trudge through the snow past a lit window. A stained-glass window nearby is full of light, but they don't see it: this is hardship, a lean time, illness or a sense of being cast out — while help is nearer than it seems. The card is about material and inner want, and about support close at hand. Its shadow is a pride that keeps you from lifting your head and asking.",
            "Не стесняйтесь попросить поддержки — вы не одни, и помощь ближе, чем кажется. День пережить трудное и найти опору.",
            "Don't hesitate to ask for support — you're not alone, and help is closer than it looks. A day to get through the hard part and find footing."),
        TarotCard("pents_06", "Шестёрка Пентаклей", "Six of Pentacles",
            "Весы в одной руке, монеты в другой — справедливый обмен. Богатый купец делится с просящими, взвешивая, кому и сколько: это щедрость, благодарность и здоровый поток даяния и получения. Аркан о балансе между тем, чтобы давать и принимать без вины. Тень — власть через подачку и зависимость, когда за помощью тянется невидимый крючок.",
            "Scales in one hand, coins in the other — a fair exchange. A well-off merchant shares with those who ask, weighing who gets how much: this is generosity, gratitude and a healthy flow of giving and receiving. The card is about the balance between giving and accepting without guilt. Its shadow is power through handouts and dependency, when a hidden hook trails behind the help.",
            "Поделитесь тем, чего в достатке, или примите помощь без чувства долга. День равновесия в том, чтобы давать и брать.",
            "Share what you have plenty of, or accept help without a sense of debt. A day of balance in giving and taking."),
        TarotCard("pents_07", "Семёрка Пентаклей", "Seven of Pentacles",
            "Пауза садовника, опершегося на мотыгу перед созревающим кустом. Пентакли уже наливаются, но плод ещё не сорван: это терпение, оценка вложенного и мудрое ожидание урожая. Аркан о том, что рост требует времени, и о трезвом взгляде на отдачу от труда. Тень — сомнение, которое бросает дело на полпути, не дождавшись сезона.",
            "A gardener's pause, leaning on the hoe before a ripening bush. The pentacles are already filling out, but the fruit is not yet picked: this is patience, a review of what you've invested and a wise wait for the harvest. The card is about growth taking time and about a sober look at the return on your labor. Its shadow is doubt that quits the work halfway, before the season comes.",
            "Оцените, что уже выросло, и наберитесь терпения — не всё созревает по требованию. День вдумчивой паузы в делах.",
            "Assess what has already grown and be patient — not everything ripens on demand. A day for a thoughtful pause in your work."),
        TarotCard("pents_08", "Восьмёрка Пентаклей", "Eight of Pentacles",
            "Ремесленник, поглощённый работой, выбивает пентакль за пентаклем. Он оттачивает мастерство в тишине, внимательный к каждой детали: это усердие, обучение через практику и рост, что рождается из самого труда. Аркан о профессионализме, сосредоточенности и малых улучшениях, из которых складывается качество. Тень — перфекционизм и работа ради работы, когда за деталями теряется смысл.",
            "A craftsman absorbed in work, hammering out pentacle after pentacle. He hones his skill in quiet, attentive to every detail: this is diligence, learning through practice and a growth born from the work itself. The card is about professionalism, focus and the small improvements that add up to quality. Its shadow is perfectionism and work for its own sake, when the meaning gets lost behind the details.",
            "Погрузитесь в работу и доведите её до качества, но помните, зачем вы её делаете. День усердия и малых, но верных улучшений.",
            "Dive into the work and bring it to quality, but remember why you're doing it. A day of diligence and small but sure improvements."),
        TarotCard("pents_09", "Девятка Пентаклей", "Nine of Pentacles",
            "Хозяйка сада среди спелых лоз, с ловчей птицей на руке. Она наслаждается достатком, добытым своим трудом: это самостоятельность, утончённость и заслуженный комфорт, в котором приятно быть наедине с собой. Аркан о независимости, изобилии и умении ценить плоды своих усилий. Тень — одиночество за красивым фасадом, когда самодостаточность отгораживает от близости.",
            "The lady of the garden among ripe vines, a hunting bird on her hand. She enjoys an abundance won by her own work: this is self-reliance, refinement and an earned comfort in which solitude feels good. The card is about independence, plenty and the ability to savor the fruits of your effort. Its shadow is loneliness behind a fine facade, when self-sufficiency walls you off from closeness.",
            "Насладитесь тем, что заработали сами, и позвольте себе гордость без вины. День самодостаточности и удовольствия от результата.",
            "Enjoy what you've earned yourself and let yourself feel pride without guilt. A day of self-sufficiency and pleasure in the result."),
        TarotCard("pents_10", "Десятка Пентаклей", "Ten of Pentacles",
            "Три поколения под аркой родового дома, где пентакли рассыпаны как достаток. Старик, пара, ребёнок и псы — это семья, наследие, прочный фундамент и благополучие, рассчитанное надолго. Аркан о стабильности, корнях и богатстве, что переживает своего владельца. Тень — жить по инерции ради того, что «положено», забыв спросить, чего хочешь сам.",
            "Three generations beneath the arch of the family home, pentacles scattered about like plenty. An old man, a couple, a child and the dogs — this is family, legacy, a solid foundation and a well-being built to last. The card is about stability, roots and wealth that outlives its owner. Its shadow is coasting on inertia for the sake of what's expected, forgetting to ask what you yourself want.",
            "Думайте вдолгую и укрепляйте основу, но сверяйтесь и с собственными желаниями. День о семье, доме и надёжных вложениях.",
            "Think long-term and strengthen the foundation, but check it against your own wishes too. A day about family, home and reliable investments."),
        TarotCard("pents_11", "Паж Пентаклей", "Page of Pentacles",
            "Юный мечтатель, что разглядывает пентакль как учебную задачу. Паж стоит в цветущем поле, увлечённый замыслом: это тяга к знанию, практическое любопытство и первый серьёзный интерес к реальному результату. Стихия земли в нём прилежна и основательна. Незрелая её сторона — планы, что застревают в мечтах и не идут дальше слов.",
            "A young dreamer studying a pentacle like a lesson to master. The Page stands in a blooming field, absorbed in an idea: this is a pull toward learning, practical curiosity and a first serious interest in a real result. The element of earth in him is diligent and thorough. Its unripe side is plans that get stuck in daydreaming and never move past words.",
            "Начните учиться новому или планировать доход — и переведите замысел в первый конкретный шаг. День прилежания и приземлённых целей.",
            "Start learning something new or planning income — and turn the idea into a first concrete step. A day of diligence and grounded goals."),
        TarotCard("pents_12", "Рыцарь Пентаклей", "Knight of Pentacles",
            "Самый неспешный из рыцарей, застывший в поле с пентаклем в руке. Его конь стоит смирно — это надёжность, методичность и терпеливое движение к цели: медленно, но верно, шаг за шагом. Аркан об ответственности, постоянстве и доведении дела до конца. Тень — рутина, что незаметно переходит в застой, и упорство, которому не хватает гибкости.",
            "The most unhurried of knights, halted in a field with a pentacle in hand. His horse stands still — this is reliability, method and patient progress toward the goal: slow but sure, step by step. The card is about responsibility, constancy and seeing things through. Its shadow is routine that slides quietly into stagnation, and a persistence that lacks flexibility.",
            "Делайте рутину без спешки — постоянство надёжно приведёт к цели. День дисциплины и порядка, но не бойтесь при нужде сменить темп.",
            "Do the routine without rushing — steadiness will get you there for certain. A day of discipline and order, but don't fear a change of pace when needed."),
        TarotCard("pents_13", "Королева Пентаклей", "Queen of Pentacles",
            "Заботливая хозяйка среди пышной зелени, с пентаклем на коленях и кроликом у ног. В ней практичность, тепло и умение обустроить жизнь так, чтобы всем было хорошо: она питает, поддерживает и держит дом на прочной земле. Аркан о заботе, уюте и щедрой основательности. Тень — забыть о себе, растворяясь в заботе обо всех вокруг.",
            "A caring mistress amid lush greenery, a pentacle in her lap and a rabbit at her feet. In her live practicality, warmth and the gift of arranging life so everyone is well: she nourishes, supports and keeps the home on firm ground. The card is about care, comfort and a generous groundedness. Its shadow is forgetting yourself while dissolving into care for everyone around.",
            "Позаботьтесь о теле, доме и близких по-хозяйски, но не в ущерб себе. День практичной доброты и уюта.",
            "Care for your body, home and loved ones in a grounded way, but not at your own expense. A day of practical kindness and comfort."),
        TarotCard("pents_14", "Король Пентаклей", "King of Pentacles",
            "Уверенный хозяин своего изобилия, восседающий среди виноградных лоз. Король держит пентакль и скипетр, окружённый плодами долгого труда: это деловая зрелость, надёжность и щедрая стабильность того, кто умеет создавать и приумножать. Аркан о достатке, ответственности и прочном результате. Тень — власть денег и упор на статус, когда вещи заслоняют людей.",
            "A confident master of his abundance, seated among the grapevines. The King holds a pentacle and a scepter, surrounded by the fruits of long labor: this is business maturity, reliability and the generous stability of someone who knows how to build and multiply. The card is about prosperity, responsibility and a solid result. Its shadow is the power of money and a focus on status, when possessions eclipse people.",
            "Управляйте ресурсами уверенно и великодушно, помня, что дело служит людям, а не наоборот. День для финансов, дела и надёжных решений.",
            "Manage resources with confidence and generosity, remembering that the work serves people, not the reverse. A day for finances, work and sound decisions."),
    )

    init {
        require(cards.size == 78) { "В колоде должно быть 78 карт, а не ${cards.size}" }
    }

    fun byId(id: String): TarotCard? = cards.firstOrNull { it.id == id }

    /** n различных случайных карт — для выбора «трёх рубашек» и для раскладов. */
    fun draw(n: Int): List<TarotCard> = cards.shuffled().take(n)
}
